/* Browser-only product walkthrough. Scenario v2 never calls external APIs. */
const L=window.LAB,E=window.DEMO_ENGINE,$=s=>document.querySelector(s);
const STORAGE='u3-product-mock-v2';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fresh=()=>({topic:'overview',b1:{stage:0,scope:'broad',results:null,approved:false,volume:'350',channel:'스마트스토어',outcome:null},b2:{stage:0,order:'mc',fixed:false,runs:[],approved:false,name:'체험 고객'},b3:{stage:0,node:'policy',project:'daily',request:'일반 고객 무료배송 기준을 5만원에서 3만원으로 변경해줘',parsed:null,selected:['policy','faq','config','tests'],contents:{},drafts:{},coverage:false,checked:false,approved:false},d:{stage:0,analyzed:false,info:false,decisions:{},reasons:{},premises:{},recorded:false,changed:false,records:[]},patent:{stage:0,description:'통신 품질에 따라 센서 데이터 압축과 샘플링 간격을 조정하는 고객용 SDK',mode:'all',expanded:false,searched:false,node:'US9986069B2',choices:{},reasons:{},saved:false},feedback:{},note:'',vote:'',visited:[]});
let state=fresh(),storageWarning='',busy=false,notice='',exportText='';
try{const saved=JSON.parse(localStorage.getItem(STORAGE)||'null');if(saved&&saved.version===2)state=saved.state;}catch{storageWarning='브라우저 저장을 사용할 수 없습니다. 이 탭 안에서만 체험을 이어갈 수 있습니다.';}
function persist(){exportText='';try{localStorage.setItem(STORAGE,JSON.stringify({version:2,state}));}catch{storageWarning='저장 공간을 사용할 수 없습니다. 결과를 내려받아 보관하세요.';}}
function badge(text,kind=''){return `<span class="badge ${kind}">${esc(text)}</span>`;}
function btn(action,label,disabled=false,secondary=false){return `<button class="${secondary?'secondary':'primary'}" data-action="${action}" ${disabled?'disabled':''}>${label}</button>`;}
function field(label,id,value,type='text'){return `<div class="field"><label for="${id}">${label}</label><input id="${id}" data-field="${id}" type="${type}" value="${esc(value)}"></div>`;}
function area(label,id,value,placeholder=''){return `<div class="field"><label for="${id}">${label}</label><textarea id="${id}" data-field="${id}" placeholder="${esc(placeholder)}">${esc(value)}</textarea></div>`;}
function select(label,id,value,items){return `<div class="field"><label for="${id}">${label}</label><select id="${id}" data-field="${id}">${items.map(([v,t])=>`<option value="${v}" ${v===value?'selected':''}>${t}</option>`).join('')}</select></div>`;}
function panel(title,body,extra=''){return `<section class="panel ${extra}"><h3>${title}</h3>${body}</section>`;}
function result(title,body,kind=''){return `<div class="result ${kind}"><h3>${title}</h3>${body}</div>`;}
function tip(label,text){const id='tip-'+label.replace(/\s/g,'-');return `<span class="hint"><button class="hint-trigger" type="button" aria-label="${esc(label)} 설명" aria-describedby="${esc(id)}" aria-expanded="false">${label} ⓘ</button><span class="tooltip" id="${esc(id)}" role="tooltip">${text}</span></span>`;}
function topicHeader(t){const s=state[t.id];return `<div class="workspace-head"><div><span class="eyebrow">${t.role} / ${t.n}</span><h2>${t.problem}</h2><p>${t.goal}</p></div><div class="controls">${btn('help','이 기능 이해하기',false,true)}${btn('reset','이 체험 초기화',false,true)}</div></div><ol class="journey">${t.steps.map((x,i)=>`<li class="${s.stage>i?'done':s.stage===i?'current':''}"><span>${s.stage>i?'✓':i+1}</span>${x}</li>`).join('')}</ol>${guidance(t,s)}`;}

function guidance(t,s){
 const context=window.REVIEW_CONTEXT[t.id],steps=context.actions,index=Math.min(s.stage,steps.length-1);
 const next=t.id==='b1'&&s.results?.some(r=>!r.correct)?'잘못 연결된 주문이 있습니다. 적용 조건을 좁히고 과거 주문을 다시 시험하세요.':steps[index];
 return `<section class="work-guide" aria-label="현재 단계와 검증 범위"><div><span class="eyebrow">${s.stage>=4?'체험 후 다음 업무':'지금 할 일'}</span><strong>${esc(next)}</strong><p>이 화면의 조작은 준비된 예시를 처리하는 시뮬레이션입니다.</p></div><details><summary>실제 검증은 어디까지 됐나요?</summary><p><strong>확인:</strong> ${esc(context.observed)}</p><p><strong>미확인:</strong> ${esc(context.unknown)}</p></details><a href="evidence.html#${t.id}">이 후보의 실제 실행 근거 ↗</a></section>`;
}

function render(){
  const topics=[{id:'overview',n:'◈',name:'주제 선택'},...L.topics,{id:'summary',n:'✓',name:'비교와 회의 의견'}];
  $('#topic-nav').innerHTML=topics.map(t=>`<button class="nav-item ${state.topic===t.id?'active':''}" data-topic="${t.id}" ${state.topic===t.id?'aria-current="page"':''}><span>${t.n}</span><span>${t.name}</span></button>`).join('');
  $('#page-title').textContent=topics.find(t=>t.id===state.topic)?.name||'주제 선택';
  $('#page-content').innerHTML=(storageWarning?result('저장 안내',esc(storageWarning),'warn'):'')+({overview,b1,b2,b3,d,patent,summary}[state.topic]||overview)();
  $('#activity-status').textContent=notice;
  if(busy)$('#page-content').querySelectorAll('button').forEach(b=>b.disabled=true);
}
function overview(){return `<div class="landing"><div class="eyebrow">U3 / PRODUCT EXPLORER</div><h2>사람의 판단이 필요한 순간,<br>어떤 일을 함께 줄일까요?</h2><p>① 사용자와 문제를 확인하고 ② 예시 업무를 체험한 뒤 ③ 실제 검증 근거를 보고 의견을 남겨 주세요.</p><p class="small">여기서 누르는 버튼은 준비된 업무의 시뮬레이션입니다. 아래 근거에서는 실제로 실행한 범위와 남은 검증을 확인합니다.</p><div class="landing-meta">${badge('각 체험 3–5분')}${badge('진행 상태는 이 브라우저에 저장','green')}${badge('가상 업무 · 준비된 문헌','gray')}</div></div><div class="topic-cards">${L.topics.map(t=>`<article class="topic-card"><span class="card-number">${t.n}</span><p class="small muted">${t.role}</p><h3>${t.name}</h3><p>${t.problem}</p><p class="small muted">${t.goal}</p><p class="small evidence-preview">실제 확인: ${esc(window.REVIEW_CONTEXT[t.id].observed)}<br>남은 확인: ${esc(window.REVIEW_CONTEXT[t.id].unknown)}</p><a class="small" href="evidence.html#${t.id}">이 후보의 실행 근거 보기 ↗</a><div class="card-bottom"><button class="primary" data-topic="${t.id}">업무 체험하기 →</button>${badge(state.visited.includes(t.id)?'체험 중':'새 체험','gray')}</div></article>`).join('')}</div>`;}
function b1(){const s=state.b1,rows=s.results;
  return topicHeader(L.topics[0])+`<div class="workspace-grid">${panel('실패 주문과 해결 이력',`<p class="small muted">상품 연결 실패와 운영자의 해결을 가정한 예시 기록입니다.</p><div class="table-wrap"><table><thead><tr><th>주문 / 채널</th><th>상품 / 용량</th><th>사람이 연결한 상품</th></tr></thead><tbody>${L.orders.map(o=>`<tr><td>${o.id}<small>${o.channel}</small></td><td>${o.name}<small>${o.volume}ml · ${o.external}</small></td><td>${o.target}<small>${o.outcome}</small></td></tr>`).join('')}</tbody></table></div>${btn('b1-group','반복 패턴 찾기')}${s.stage>0?result('코드가 같은 사건 4건','<p>350ml 단품 2건은 같은 상품으로 해결했습니다. 500ml와 자사몰 세트 상품은 연결 대상이 다릅니다.</p>','warn'):''}`)}
  <div class="stack">${panel('규칙 후보 · 사람의 적용 범위',`<p><strong>MUG-WHT → SKU-MUG-350-W</strong></p>${select('적용 조건','b1-scope',s.scope,[['broad','외부 상품코드만 일치'],['safe','스마트스토어 + 350ml + 외부 코드 일치']])}<p class="small muted">${tip('과거 재시험','승인할 규칙을 과거 주문에 적용해 원래 해결 결과와 비교합니다.')}에서 다른 상품이 잘못 연결되는지 확인합니다.</p><div class="controls">${btn('b1-replay','과거 주문 재시험',s.stage<1)}${btn('b1-approve','이 조건으로 자동 적용 승인',!rows||rows.some(r=>!r.correct)||!rows.some(r=>r.matched)||s.approved)}</div>${rows?result(rows.some(r=>!r.correct)?'승인 보류 · 잘못된 매핑 발견':'시험 통과 · 승인 가능한 범위',`<ul>${rows.map(r=>`<li><strong>${r.id}</strong> · ${esc(r.channel??L.orders.find(o=>o.id===r.id)?.channel)} / ${esc(r.volume??L.orders.find(o=>o.id===r.id)?.volume)}ml<br>제안: ${esc(r.matched?'SKU-MUG-350-W':'자동 적용 보류')} · 예시 해결: ${esc(r.historical??L.orders.find(o=>o.id===r.id)?.target)}<br>${r.matched?(r.correct?'같은 상품으로 연결':'다른 상품으로 잘못 연결 → 조건을 좁혀 재시험'):'채널 또는 용량이 승인 조건과 다름 → 사람 확인'}</li>`).join('')}</ul>`,rows.some(r=>!r.correct)?'warn':'success'):''}`)}
  ${panel('새 주문 O-1201 처리',`<div class="controls">${select('판매 채널','b1-channel',s.channel,[['스마트스토어','스마트스토어'],['자사몰','자사몰']])}${select('상품 용량','b1-volume',s.volume,[['350','350ml 단품'],['500','500ml 단품']])}</div>${btn('b1-process','새 주문 처리',!s.approved)}${s.outcome?result(s.outcome.auto?'자동 매핑 완료':'담당자 확인으로 보류',`<p>${esc(s.outcome.message)}</p>`,s.outcome.auto?'success':'warn'):''}`)}</div></div>`;
}
function b2(){const s=state.b2;const runs=s.runs;
  return topicHeader(L.topics[1])+`<div class="workspace-grid">${panel('신규 문의를 처리하는 두 자동화',`<div class="flow-node">신규 문의 접수 <span>→</span> 고객 C-204</div><div class="flow-branches"><div class="flow-node">마케팅 흐름<small>고객 상태 → 관심 고객</small></div><div class="flow-node ${s.fixed?'resolved':'collision'}">CS 흐름<small>${s.fixed?'CS 처리 상태':'고객 상태'} → 처리 완료</small></div></div><div class="shared-data">${tip('공유 필드','두 흐름이 같은 고객의 같은 필드를 덮어쓰면 실행 순서에 따라 최종 값이 달라질 수 있습니다.')}<strong>${s.fixed?'customer.status / customer.cs_status':'customer.status'}</strong></div>${field('시험 고객 이름','b2-name',s.name)}${btn('b2-scan','배포 전 충돌 검사')}${s.stage>0?result(s.fixed?'쓰기 대상이 분리됐습니다':'같은 고객 상태를 서로 다르게 씁니다',`<p>${s.fixed?'격리 재시험으로 두 상태가 모두 보존되는지 확인하세요.':'마케팅과 CS의 정보가 한 필드에 섞였습니다. 실행 순서를 바꿔 결과를 확인하세요.'}</p>`,s.fixed?'success':'warn'):''}`)}
  <div class="stack">${panel('예시 순서별 실행 비교',`${select('실행 순서','b2-order',s.order,[['mc','마케팅 → CS'],['cm','CS → 마케팅']])}<div class="controls">${btn('b2-run','이 순서로 시뮬레이션',s.stage<1)}${btn('b2-both','두 순서 비교',s.stage<1,false)}</div>${runs.map(r=>`<div class="record"><h4>${r.order==='mc'?'마케팅 → CS':'CS → 마케팅'}</h4><div class="timeline">${r.output.trace.map(x=>`<p>${x.flow==='marketing'?'마케팅':'CS'} 실행 → 고객 상태 <strong>${esc(x.customer.status)}</strong>${x.customer.cs_status?' / CS '+esc(x.customer.cs_status):''}</p>`).join('')}</div><p>최종: ${esc(r.output.customer.name)} · ${esc(r.output.customer.status)}${r.output.customer.cs_status?' · CS '+esc(r.output.customer.cs_status):''}</p></div>`).join('')}`)}
  ${panel('수정과 배포 판단',`<p>마케팅 관계와 CS 처리 상태를 별도 필드에 보관합니다.</p><div class="controls">${btn('b2-fix','CS 전용 상태 필드로 수정',!runs.length||s.fixed)}${btn('b2-approve','재시험 결과 승인',!s.fixed||runs.length<2||s.approved)}</div>${s.approved?result('배포 승인 기록','<p>두 실행 순서에서 관심 고객과 CS 처리 완료가 모두 보존됐습니다. 별도 실제 n8n 검증에서도 통제 입력의 두 순서를 확인했습니다. 다음 단계는 회사 업무 조건과 실행 이력을 확보해 확인하는 것입니다.</p>','success'):''}`)}</div></div>`;
}
function b3(){const s=state.b3,a=L.artifacts.find(x=>x.id===s.node),content=s.contents[a.id]||a.before;const checks=E.shippingCheck(L.artifacts,s.contents,s.coverage),issues=checks.filter(x=>!['unrelated','updated'].includes(x.status));
  const status={updated:'새 값 확인',stale:'이전 기준 남음',mixed:'문맥 확인',uncertain:'문맥 확인',coverage:'경계값 검증 부족',unrelated:'영향 없음'};
  return topicHeader(L.topics[2])+`${panel('데일리숍 / 일반 고객 배송 정책',`<div class="controls"><strong>고정 예시: 데일리숍 · 배송 정책</strong><span class="small muted">업무 구조 7개 자료 · 프로젝트 사본</span></div>${area('변경 요청','b3-request',s.request)}${btn('b3-parse','요청 해석하기')}${s.parsed?result(s.parsed.ok?'적용할 변경을 확인해 주세요':'지원 범위를 확인해 주세요',`<p>${esc(s.parsed.message)}</p>${s.parsed.ok?btn('b3-confirm','이 변경으로 영향 범위 확인'):''}`,s.parsed.ok?'':'warn'):''}`)}
  <div class="project-layout"><section class="panel tree-panel"><h3>프로젝트 구조</h3><p class="small muted">항목을 누르면 내용과 연결 근거가 보입니다.</p>${[...new Set(L.artifacts.map(x=>x.group))].map(g=>`<details open><summary>${g}</summary>${L.artifacts.filter(x=>x.group===g).map(x=>`<button class="tree-node ${x.id===s.node?'selected':''}" data-node="${x.id}"><span>${x.name}</span>${s.checked?badge(status[checks.find(c=>c.id===x.id).status],checks.find(c=>c.id===x.id).status==='updated'?'green':'gray'):''}</button>`).join('')}</details>`).join('')}</section>
  ${panel(a.name,`<p class="small muted">${esc(a.why)}</p><div class="diff-grid"><div><span class="eyebrow">변경 전</span><pre>${esc(a.before)}</pre></div><div><span class="eyebrow">현재 프로젝트 사본</span><pre>${esc(content)}</pre></div></div>${area('자료 직접 편집','b3-edit',s.drafts?.[a.id]??content)}<div class="controls">${btn('b3-save','편집 내용 저장',s.stage<1,true)}${btn('b3-add',s.selected.includes(a.id)?'영향 범위에서 제외':'영향 범위에 추가',s.stage<1,true)}</div><p class="small">현재 영향 판단: <strong>${s.selected.includes(a.id)?'반영 대상':'반영 대상 아님'}</strong></p>${a.id==='tests'?`<p class="small">50,000원 테스트를 삭제할 필요는 없습니다. 새 경계값 29,999원·30,000원이 필요합니다.</p>${btn('b3-tests','새 경계값 검사 시뮬레이션',s.stage<2,true)}`:''}`)}</div>
  ${panel('영향 범위와 변경 실행',`<div class="chip-list">${s.selected.map(id=>badge(L.artifacts.find(a=>a.id===id).name)).join('')}</div><p class="small muted">근거를 확인한 항목만 반영하세요. 후보에서 빠진 항목은 트리에서 추가할 수 있습니다.</p><div class="controls">${btn('b3-apply','선택한 자료에 변경 반영',s.stage<1)}${btn('b3-check','반영 결과 검사',s.stage<2,true)}</div>${s.checked?result(issues.length?'완료 보류 · '+issues.length+'개 항목 확인':'모든 영향 항목 확인 · 완료 승인 가능',`<div class="check-list">${checks.map(c=>`<div><strong>${L.artifacts.find(a=>a.id===c.id).name}</strong>${badge(status[c.status],c.status==='updated'?'green':'gray')}<p>${esc(c.message)}</p></div>`).join('')}</div>${issues.length?`${issues.some(x=>x.id==='cs')?btn('b3-report','상담 문구 보정 → 영향 범위에 추가',false,true):''}${issues.some(x=>x.status==='coverage')?btn('b3-tests','부족한 경계값 검사 추가',false,true):''}<p class="small">위에서 표시된 문제 자료를 선택해 편집·반영한 뒤 다시 검사하세요.</p>`:btn('b3-approve','변경 완료 승인',s.approved)}${s.approved?'<p><strong>변경 완료 기록을 남겼습니다.</strong> 일반 고객 배송비 안내·설정과 새 경계값 테스트를 확인했습니다.</p>':''}`,issues.length?'warn':'success'):''}`)}`;
}
function d(){const s=state.d;return topicHeader(L.topics[3])+`${panel('SenseFlow SDK 2.0 · 고객 배포 예정',`<div class="release-bar"><div><span class="eyebrow">공개 사건</span><h3>고객 단말에서 센서 데이터 처리</h3><p>가상 일정: 10/07 배포 · 변경 4건 · 공개 전 확인</p></div>${badge(s.changed?'공개 범위 변경됨':'SDK 공개 준비','amber')}</div>${btn('d-analyze','개발 변경과 과거 판단 연결')}`)}
  ${s.analyzed?`<div class="event-grid">${L.events.map(x=>`<section class="panel event-card"><div class="panel-head"><h3>${x.title}</h3>${badge(x.id==='buffer'&&s.info?'검토 정보 확보':x.signal,x.kind==='skip'?'gray':'amber')}</div><p>${x.id==='buffer'&&s.info?'예시 확인 답변: 서버 내부 로그 버퍼 크기만 조정했습니다. SDK에 구현을 포함하지 않습니다.':esc(x.text)}</p><div class="prior-record"><strong>${esc(x.prior)}</strong><p>${x.premise?esc(x.premise):x.kind==='skip'?'구현 변경 없이 화면만 조정한 기록입니다.':'과거 판단과 연결할 정보가 필요합니다.'}</p></div>${x.id==='buffer'&&!s.info?btn('d-info','준비된 공개 범위 답변 보기',false,true):''}${select('담당자의 처리','d-choice-'+x.id,s.decisions[x.id]||'pending',[['pending','아직 판단하지 않음'],['review','IP 담당자에게 검토 요청'],['hold','정보 부족으로 보류'],['skip','추가 검토 불필요']])}${area('판단 이유','d-reason-'+x.id,s.reasons[x.id]||'','어떤 근거를 확인했는지 적어 주세요')}${x.id==='sdk'?select('이번 판단에서 가정한 공개 범위','d-scope',s.scope||'server',[['server','서버 내부 유지'],['sdk','고객 SDK에 바이너리 포함']])+area('이번 판단의 전제','d-premise-sdk',s.premises.sdk||'','선택한 공개 범위와 검토 조건을 본인 표현으로 적어 주세요') :''}</section>`).join('')}</div>${panel('검토 작업과 판단 전제',`<div class="controls">${btn('d-record','판단 기록과 후속 작업 만들기')}${btn('d-change','다음 릴리스: 공개 범위 확대',!s.recorded||!s.premises.sdk||!s.decisions.sdk||s.decisions.sdk==='hold'||s.changed,true)}</div>${s.recorded?result('담당자의 후속 작업',`<ul>${L.events.map(x=>`<li>${x.title}: ${esc({review:'IP 검토 작업 생성',hold:'추가 정보 요청 대기',skip:'검토 제외 기록'}[s.decisions[x.id]]||'미판단')}</li>`).join('')}</ul><p>기록된 전제: ${esc(s.premises.sdk||'없음')}</p>`):''}${s.changed?result('재검토 요청 · 공개 범위가 달라졌습니다',`<p>저장한 전제: ${esc(s.premises.sdk)}</p><p>현재: ${s.scope==='sdk'?'바이너리 제공에서 구현 원문 공개로 확대할 계획입니다.':'서버 내부 유지에서 고객 SDK 포함으로 확대할 계획입니다.'} 이전 기록을 보존하고 IP 담당자에게 전제가 유효한지 다시 확인하는 작업을 만들었습니다.</p>`,'warn'):''}`)}`:panel('변경 목록',L.events.map(x=>`<div class="record"><h4>${x.title}</h4><p>${esc(x.text)}</p></div>`).join(''))}`;}
function patent(){const s=state.patent,list=s.searched?E.patentFilter(L.patents,s.description,s.mode,s.expanded):[],doc=L.patents.find(x=>x.id===s.node)||L.patents[0];
  return topicHeader(L.topics[4])+`${panel('SenseFlow / 비교할 기술',`${area('기술 설명','patent-description',s.description)}<div class="controls">${select('검색 관점','patent-mode',s.mode,[['all','압축 + 샘플링'],['compression','데이터 압축'],['sampling','샘플링 조정'],['power','센서 전력 절감']])}${btn('patent-search','준비된 공개 문헌에서 찾기')}</div><p class="small muted">2026/09/30 확인한 공개 문헌 3건을 대상으로 탐색합니다. 표시 순서는 준비한 문헌 순서이며 검색 순위·실시간 API 결과가 아닙니다.</p>`)}
  ${s.searched?`<div class="project-layout"><section class="panel tree-panel"><h3>검토 후보 ${list.length}건</h3>${list.length?list.map(p=>`<button class="patent-node ${p.id===s.node?'selected':''}" data-patent="${p.id}"><strong>${p.id}</strong><span>${esc(p.summary)}</span>${badge(s.choices[p.id]==='include'?'검토 대상':s.choices[p.id]==='exclude'?'제외':'미판단',s.choices[p.id]==='include'?'green':'gray')}</button>`).join(''):'<p>지원 기술을 찾지 못했습니다. 센서 데이터 압축·샘플링·전력 절감 설명으로 시험해 주세요.</p>'}${btn('patent-expand','범위 확대 · 센서 전력 절감 포함',!list.length||s.expanded,true)}</section>${list.some(p=>p.id===doc.id)?panel('기술 설명과 원문 근거 비교',`<span class="eyebrow">${doc.id}</span><h3>${esc(doc.title)}</h3><div class="diff-grid"><div><h4>우리 기술 설명</h4><p>${esc(s.description)}</p></div><div><h4>${doc.section}</h4><blockquote lang="en">${esc(doc.quote)}</blockquote><p>${esc(doc.interpretation)}</p><a href="${doc.url}" target="_blank" rel="noopener noreferrer">공개 문헌 원문 열기 ↗</a></div></div><div class="result"><strong>비교할 질문</strong><p>${esc(doc.question)}</p></div><p class="small muted">한국어 설명은 원문을 읽기 위한 요약입니다. 짧은 발췌로 청구항 전체의 범위·관련성을 확정하지 않습니다.</p>${select('사람의 검토 판단','patent-choice',s.choices[doc.id]||'pending',[['pending','판단 전'],['include','후속 검토 대상에 추가'],['exclude','이번 검토에서 제외'],['hold','추가 자료 확인 후 판단']])}${area('판단 이유·확인할 차이','patent-reason',s.reasons[doc.id]||'')}${btn('patent-save','검토 기록 저장')}`):panel('문헌 선택','후보를 선택하면 실제 원문 근거와 비교 질문이 표시됩니다.')}</div>${s.saved?panel('저장한 검토 목록',Object.entries(s.choices).filter(([,v])=>v!=='pending').map(([id,v])=>`<div class="record"><strong>${id}</strong> ${badge({include:'후속 검토',exclude:'제외',hold:'보류'}[v])}<p>${esc(s.reasons[id]||'이유 미기록')}</p></div>`).join('')):''}`:''}`;
}
function summary(){return `<div class="workspace-head"><div><span class="eyebrow">MEETING / TOPIC COMPARISON</span><h2>우리 팀이 풀고 싶은 문제를 고르세요</h2><p>체험의 재미와 실제 업무의 필요성을 함께 생각해 주세요.</p></div></div><div class="comparison-grid">${L.topics.map(t=>panel(t.n+' · '+t.name,`<p class="small">${t.role} · ${t.problem}</p>${['empathy','use','data','human'].map((key,i)=>select(['문제 공감도','활용 장면이 그려지는가','자료를 확보할 수 있는가','사람 판단이 필요한가'][i],'rate-'+t.id+'-'+key,state.feedback[t.id]?.[key]||'',[['','아직 평가 안 함'],['1','1 · 낮음'],['2','2'],['3','3 · 보통'],['4','4'],['5','5 · 높음']])).join('')}`)).join('')}</div>${panel('회의 의견 보관',`${select('우선 논의할 후보','meeting-vote',state.vote,[['','아직 선택하지 않음'],...L.topics.map(t=>[t.id,t.name])])}${area('선택 이유와 확보할 수 있는 자료','meeting-note',state.note)}<div class="controls">${btn('export','회의 의견 파일 준비')}</div>${exportText?`<div class="result success"><p>판단·이유·평가를 포함한 파일을 준비했습니다.</p><a class="primary download-link" id="download-feedback" download="u3-meeting-feedback.json" href="data:application/json;charset=utf-8,${encodeURIComponent(exportText)}">JSON 파일 내려받기</a><details><summary>파일 내용 보기 · 다운로드가 안 되면 복사</summary><textarea readonly aria-label="회의 의견 JSON">${esc(exportText)}</textarea></details></div>`:''}<p class="small muted">서버에 자동 제출되지 않습니다. 파일을 회의 진행자에게 직접 전달하세요. 브라우저 저장 기록은 ‘이 체험 초기화’로 주제별 초기화할 수 있습니다.</p>`)} `;}
function showHelp(){const t=L.topics.find(t=>t.id===state.topic);if(!t){$('#help-title').textContent='주제 비교 안내';$('#help-body').innerHTML='<p>각 주제의 업무 체험하기를 눌러 입력부터 결과까지 처리해 보세요. 주제 안의 도움말은 사용자·문제·시스템 역할·사람 판단과 다음 작업을 설명합니다.</p><p>비교와 회의 의견에서 문제 공감도, 활용 장면, 자료 확보 가능성, 사람 판단의 필요성을 평가합니다. 의견 파일을 내려받아 회의 진행자에게 전달해 주세요.</p><p>업무는 가상이며 실제 시스템과 연동하지 않습니다. 입력은 이 브라우저에만 저장됩니다.</p>';$('#help-dialog').showModal();return;}$('#help-title').textContent=t.name+' · 이 기능 이해하기';$('#help-body').innerHTML=`<p>${t.guide}</p><dl class="help-dl"><dt>누가 쓰나요?</dt><dd>${t.role}</dd><dt>어떤 문제인가요?</dt><dd>${t.problem}</dd><dt>시스템은 무엇을 하나요?</dt><dd>${t.system}</dd><dt>사람은 무엇을 결정하나요?</dt><dd>${t.human}</dd><dt>무엇을 해보나요?</dt><dd>${t.goal}</dd><dt>실제 개발에 필요한 자료</dt><dd>${t.data}</dd></dl><h3>이 화면의 범위와 출처</h3><p>${t.id==='patent'?'기술 설명과 업무는 가상입니다. 공개 문헌 3건의 제목·짧은 원문 발췌는 출처에서 확인한 자료입니다. 기존 KIPRIS 성능 평가와 별개의 목업입니다.':'가상 프로젝트의 준비된 자료와 규칙으로 처리합니다. 실제 시스템 연동이나 현장 성능 검증 결과가 아닙니다.'}</p><a href="${t.source}" target="_blank" rel="noopener noreferrer">참고한 업무 흐름: ${t.sourceName} ↗</a><p>평가 근거: B-3·D 기존 제작 사례와 KIPRIS 실험은 별도 기록에 보존되어 있습니다. 이 체험에서 얻는 점수는 팀 의견입니다.</p>`;$('#help-dialog').showModal();}
function changeTopic(id){state.topic=id;notice='';if(L.topics.some(t=>t.id===id)&&!state.visited.includes(id))state.visited.push(id);persist();render();$('#page-content').focus();window.scrollTo({top:0,behavior:'instant'});}
function payload(){return {schema:'u3-product-feedback-v2',created_at:new Date().toISOString(),data_kind:'scenario_mock_with_curated_public_patent_excerpts',feedback:state.feedback,vote:state.vote,note:state.note,progress:{b1:state.b1,b2:state.b2,b3:state.b3,d:state.d,patent:state.patent}};}
async function perform(action){
  if(action==='help'){showHelp();return;}
  if(action==='reset'){const id=state.topic;state[id]=fresh()[id];notice='이 주제의 체험을 초기화했습니다.';persist();render();return;}
  if(action==='export'){exportText=JSON.stringify(payload(),null,2);notice='회의 의견 파일을 준비했습니다.';render();return;}
  if(busy)return;busy=true;notice='작업 중…';render();await new Promise(resolve=>setTimeout(resolve,240));
  const a=state.b1,b=state.b2,c=state.b3,q=state.d,p=state.patent;
  switch(action){
    case 'b1-group':a.stage=Math.max(a.stage,1);notice='같은 코드의 해결 이력과 다른 상품 조건을 찾았습니다.';break;
    case 'b1-replay':a.results=E.replay(L.orders,a.scope);a.stage=2;a.approved=false;notice='예시 주문 4건의 준비된 해결 이력과 비교했습니다.';break;
    case 'b1-approve':if(a.results&&a.results.every(r=>r.correct)&&a.results.some(r=>r.matched)){a.approved=true;a.stage=3;notice='시험한 조건으로 규칙을 승인했습니다.';}break;
    case 'b1-process':if(a.approved){const match=E.mappingMatch({external:'MUG-WHT',volume:Number(a.volume),channel:a.channel},a.scope);a.outcome={auto:match,message:match?'O-1201 → SKU-MUG-350-W · 출고 대기 상태로 전환했습니다.':'승인 범위 밖입니다. 상품 용량·판매 채널을 확인하는 작업을 만들었습니다.'};a.stage=4;notice=a.outcome.message;}break;
    case 'b2-scan':b.stage=1;notice=b.fixed?'공유 쓰기 충돌 후보가 없습니다.':'고객 상태 필드의 쓰기 충돌을 찾았습니다.';break;
    case 'b2-run':case 'b2-both':if(b.stage>=1){b.runs=(action==='b2-both'?['mc','cm']:[b.order]).map(order=>({order,output:E.crmRun(order==='mc'?['marketing','cs']:['cs','marketing'],b.fixed,{name:b.name,status:'신규 문의'})}));b.stage=b.fixed?3:2;b.approved=false;notice='시험 입력에서 실행 결과를 계산했습니다.';}break;
    case 'b2-fix':if(b.runs.length){b.fixed=true;b.runs=[];b.stage=2;b.approved=false;notice='CS 전용 상태 필드를 추가했습니다. 두 순서를 다시 시험하세요.';}break;
    case 'b2-approve':if(b.fixed&&b.runs.length===2){b.approved=true;b.stage=4;notice='격리 재시험 결과를 승인했습니다.';}break;
    case 'b3-parse':c.parsed=E.parseShippingRequest(c.request);notice=c.parsed.message;break;
    case 'b3-confirm':if(c.parsed?.ok){c.stage=Math.max(c.stage,1);notice='영향 후보 4개를 표시했습니다. 상담 문구 누락을 포함해 직접 범위를 보정할 수 있습니다.';}break;
    case 'b3-add':if(c.stage>=1){c.selected=c.selected.includes(c.node)?c.selected.filter(x=>x!==c.node):[...c.selected,c.node];c.checked=false;c.approved=false;notice='영향 범위를 변경했습니다.';}break;
    case 'b3-save':if(c.stage>=1){c.contents[c.node]=c.drafts?.[c.node]??c.contents[c.node]??L.artifacts.find(x=>x.id===c.node).before;if(c.node==='tests')c.coverage=false;if(c.drafts)delete c.drafts[c.node];c.checked=false;c.approved=false;notice='프로젝트 사본에 편집 내용을 저장했습니다.';}break;
    case 'b3-apply':if(c.stage>=1){for(const x of L.artifacts){if(c.selected.includes(x.id)&&x.affected&&x.id!=='tests')c.contents[x.id]=x.after;if(c.drafts)delete c.drafts[x.id];}c.stage=2;c.checked=false;c.approved=false;notice='선택한 연결 자료를 반영했습니다. 테스트는 별도로 경계값을 추가해야 합니다.';}break;
    case 'b3-tests':if(c.stage>=2){c.coverage=true;c.contents.tests=L.artifacts.find(x=>x.id==='tests').after;if(c.drafts)delete c.drafts.tests;c.checked=false;c.approved=false;notice='새 경계값 2건과 기존 5만원 검사의 통과 결과를 시뮬레이션했습니다. 실제 실행은 근거 기록에서 확인하세요.';}break;
    case 'b3-check':if(c.stage>=2){c.checked=true;c.stage=3;notice='영향 자료 전체의 현재 상태를 검사했습니다.';}break;
    case 'b3-report':if(!c.selected.includes('cs'))c.selected.push('cs');c.node='cs';c.checked=false;c.approved=false;notice='상담 문구 누락을 기록하고 반영 대상에 추가했습니다. 변경 반영 후 다시 검사하세요.';break;
    case 'b3-approve':if(E.shippingCheck(L.artifacts,c.contents,c.coverage).every(x=>['updated','unrelated'].includes(x.status))){c.approved=true;c.stage=4;notice='변경 완료 기록을 남겼습니다.';}break;
    case 'd-analyze':q.analyzed=true;q.stage=Math.max(q.stage,1);notice='변경 4건을 공개 일정과 과거 판단에 연결했습니다.';break;
    case 'd-info':q.info=true;q.stage=2;notice='준비된 확인 답변을 표시했습니다. 이 예시에서 버퍼 개선은 서버 내부 변경입니다.';break;
    case 'd-record':{
      const missing=L.events.filter(x=>!q.decisions[x.id]||q.decisions[x.id]==='pending'||!(q.reasons[x.id]||'').trim());
      if(missing.length){notice='기록을 보류했습니다. 네 항목 모두 처리 방법과 판단 이유를 적어 주세요.';break;}
      const premise=q.premises.sdk||$('#d-premise-sdk')?.value;
      if(!(premise||'').trim()){notice='SDK 판단의 전제를 적어 주세요.';break;}

      q.premises.sdk=premise;(q.records ||= []).push({at:new Date().toISOString(),decisions:{...q.decisions},reasons:{...q.reasons},premise,scope:q.scope||'server'});q.recorded=true;q.stage=3;notice='판단 이유·전제·공개 범위와 후속 작업을 저장했습니다.';break;
    }
    case 'd-change':if(q.recorded&&q.decisions.sdk!=='hold'){q.changed=true;q.stage=4;notice='선택한 공개 범위보다 넓은 후속 계획을 시뮬레이션해 재검토 카드를 만들었습니다.';}break;
    case 'patent-search':p.searched=true;p.expanded=false;p.stage=1;{const found=E.patentFilter(L.patents,p.description,p.mode,false);p.node=found[0]?.id||'';notice=found.length?'준비된 문헌에서 후보를 찾았습니다.':'지원 범위의 센서 기술 설명을 입력해 주세요.';}break;
    case 'patent-expand':p.expanded=true;p.stage=2;notice='센서 전력 절감 문헌까지 범위를 확대했습니다.';break;
    case 'patent-save':if(!p.searched){notice='기술 설명을 변경했습니다. 후보를 다시 탐색하세요.';break;}if(!p.choices[p.node]||p.choices[p.node]==='pending'||!(p.reasons[p.node]||'').trim()){notice='저장하려면 검토 판단과 이유를 입력해 주세요.';}else{p.saved=true;p.stage=4;notice='문헌의 검토 판단과 이유를 저장했습니다.';}break;
  }
  busy=false;persist();render();
}
document.addEventListener('click',event=>{
  const el=event.target.closest('[data-topic],[data-action],[data-node],[data-patent],.hint-trigger');if(!el)return;
  if(el.matches('.hint-trigger')){const open=el.getAttribute('aria-expanded')==='true';el.setAttribute('aria-expanded',String(!open));el.closest('.hint').classList.toggle('dismissed',open);return;}
  if(busy)return;
  if(el.dataset.topic)changeTopic(el.dataset.topic);
  else if(el.dataset.node){state.b3.node=el.dataset.node;persist();render();}
  else if(el.dataset.patent){state.patent.node=el.dataset.patent;state.patent.stage=Math.max(state.patent.stage,2);persist();render();}
  else perform(el.dataset.action);
});
function updateField(event){const id=event.target.dataset.field,v=event.target.value;if(!id)return;
  if(id==='b1-scope'){state.b1.scope=v;state.b1.results=null;state.b1.approved=false;state.b1.outcome=null;state.b1.stage=Math.min(state.b1.stage,1);}
  else if(id==='b1-volume'||id==='b1-channel'){state.b1[id.slice(3)]=v;state.b1.outcome=null;}
  else if(id==='b2-name'){state.b2.name=v;state.b2.runs=[];state.b2.approved=false;state.b2.stage=Math.min(state.b2.stage,state.b2.fixed?2:1);}
  else if(id==='b2-order')state.b2.order=v;
  else if(id==='b3-edit'){(state.b3.drafts ||= {})[state.b3.node]=v;}
  else if(id==='b3-request'){state.b3.request=v;state.b3.parsed=null;}
  else if(id.startsWith('d-choice-')){state.d.decisions[id.slice(9)]=v;state.d.recorded=false;state.d.changed=false;state.d.stage=Math.min(state.d.stage,2);}
  else if(id.startsWith('d-reason-')){state.d.reasons[id.slice(9)]=v;state.d.recorded=false;state.d.changed=false;state.d.stage=Math.min(state.d.stage,2);}
  else if(id==='d-scope'){state.d.scope=v;state.d.recorded=false;state.d.changed=false;state.d.stage=Math.min(state.d.stage,2);}
  else if(id==='d-premise-sdk'){state.d.premises.sdk=v;state.d.recorded=false;state.d.changed=false;state.d.stage=Math.min(state.d.stage,2);}
  else if(id==='patent-description'||id==='patent-mode'){state.patent[id.slice(7)]=v;state.patent.searched=false;state.patent.stage=0;}
  else if(id==='patent-choice'){state.patent.choices[state.patent.node]=v;state.patent.saved=false;}
  else if(id==='patent-reason'){state.patent.reasons[state.patent.node]=v;state.patent.saved=false;}
  else if(id.startsWith('rate-')){const [,topic,key]=id.split('-');(state.feedback[topic]||= {})[key]=v;exportText='';}
  else if(id==='meeting-note'){state.note=v;exportText='';}
  else if(id==='meeting-vote'){state.vote=v;exportText='';}
  persist();
  if(event.type==='change'&&!event.target.matches('textarea,input'))render();
}
document.addEventListener('input',updateField);document.addEventListener('change',updateField);
document.addEventListener('keydown',event=>{if(event.key==='Escape')document.querySelectorAll('.hint-trigger').forEach(x=>{x.setAttribute('aria-expanded','false');x.closest('.hint').classList.add('dismissed');});});
document.addEventListener('focusin',event=>event.target.closest('.hint')?.classList.remove('dismissed'));
document.addEventListener('mouseover',event=>event.target.closest('.hint')?.classList.remove('dismissed'));
$('#help-close').onclick=()=>$('#help-dialog').close();$('#floating-help').onclick=showHelp;$('#summary-button').onclick=()=>changeTopic('summary');
render();
