(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.SERVICE_ENGINE=api;})(typeof window==='undefined'?globalThis:window,()=>{
 const terms=s=>String(s||'').toLowerCase().replace(/오브젝트|물체/g,'객체').replace(/거리\s*측정/g,'거리측정').match(/[a-z0-9_.]+|[가-힣]+/g)||[];
 function search(records,query){const words=[...new Set(terms(query))];if(!words.length)return [];return records.map(r=>{const title=terms(r.title+' '+(r.keywords||'')).join(' '),body=terms(r.abstract||r.summary||'').join(' ');const matches=words.filter(w=>title.includes(w)||body.includes(w));return {...r,score:matches.reduce((n,w)=>n+(title.includes(w)?3:1),0),matches};}).filter(r=>r.score).sort((a,b)=>b.score-a.score||a.id.localeCompare(b.id));}
 function workflow(w){if(!w||!Array.isArray(w.nodes)||!w.connections||typeof w.connections!=='object')throw Error('nodes 배열과 connections 객체가 필요합니다.');if(w.nodes.length>200)throw Error('노드는 200개까지 지원합니다.');const writes=[],unknown=[];
  for(const node of w.nodes){const p=node.parameters||{};if(node.disabled===true||node.type==='n8n-nodes-base.manualTrigger')continue;
   if(node.type!=='n8n-nodes-base.httpRequest'){unknown.push(node.name+': 지원하지 않는 노드');continue;}
   if(['GET','HEAD'].includes((p.method||'GET').toUpperCase()))continue;
   if(!['POST','PUT','PATCH'].includes((p.method||'GET').toUpperCase())||p.sendBody!==true){unknown.push(node.name+': 본문 쓰기 활성 조건 확인 필요');continue;}
   if(typeof p.url!=='string'||p.url.includes('{{')){unknown.push(node.name+': 동적 URL');continue;}
   let u,body;try{u=new URL(p.url);if(!['https:','http:'].includes(u.protocol))throw Error();body=typeof p.jsonBody==='string'?JSON.parse(p.jsonBody):p.jsonBody;}catch{unknown.push(node.name+': URL/JSON 본문 확인 필요');continue;}
   if(!body||typeof body!=='object'||Array.isArray(body)||p.specifyBody!=='json'||Object.values(body).some(v=>typeof v==='object'||String(v).includes('{{'))){unknown.push(node.name+': 정적 JSON 쓰기만 분석 가능');continue;}
   for(const [field,value]of Object.entries(body))writes.push({node:node.name,resource:u.origin+u.pathname+u.search,field,value});
  }return {name:w.name||'이름 없는 흐름',writes,unknown};
 }
 function compare(a,b){const A=workflow(a),B=workflow(b),conflicts=[];for(const x of A.writes)for(const y of B.writes)if(x.resource===y.resource&&x.field===y.field)conflicts.push({resource:x.resource,field:x.field,first:x.value,second:y.value,kind:x.value===y.value?'같은 값 중복 쓰기':'다른 값 덮어쓰기'});return {a:A,b:B,conflicts,unknown:[...A.unknown,...B.unknown]};}
 function outcomes(a,b){const r=compare(a,b);if(r.unknown.length)throw Error('미해석 노드가 있어 결과 예측을 보류합니다.');if(!r.a.writes.length||!r.b.writes.length)throw Error('두 흐름의 정적 쓰기를 확인해야 합니다.');
  if([r.a,r.b].some(flow=>new Set(flow.writes.map(w=>w.node)).size>1))throw Error('결과 계산은 흐름별 쓰기 노드 하나만 지원합니다. 다중 노드의 연결·순서는 별도 확인해야 합니다.');
  function run(flows){const result=Object.create(null);for(const flow of flows)for(const w of flow.writes){(result[w.resource]||=Object.create(null))[w.field]=w.value;}return result;}
  return {ab:run([r.a,r.b]),ba:run([r.b,r.a]),note:'정적 JSON 덮어쓰기 모델의 결과 계산. 원격 API 실행이 아닙니다.'};
 }
 function project(p){if(!p||!Array.isArray(p.artifacts)||!p.artifacts.length||p.artifacts.length>100)throw Error('artifacts 배열은 1~100개 파일이어야 합니다.');const seen=new Set();for(const f of p.artifacts){if(typeof f.path!=='string'||!f.path||seen.has(f.path)||typeof f.content!=='string'||f.content.length>100000||!['general','config','tests','unrelated','review'].includes(f.scope))throw Error('중복 경로·잘못된 내용·지원하지 않는 scope가 있습니다.');seen.add(f.path);}return p;}
 const amountPatterns=()=>/(?<![0-9,가-힣])(?:50,?000(?![0-9,])|5\s*만\s*원|오만\s*원)/g;
 function updateProject(p,paths){project(p);const copy=JSON.parse(JSON.stringify(p));for(const f of copy.artifacts){if(!paths.includes(f.path))continue;if(f.scope==='general'){const matches=[...f.content.matchAll(amountPatterns())];if(matches.length&&(matches.length>1||/(적립|쿠폰|한도|VIP|상품권)/i.test(f.content)))throw Error('여러 금액·정책이 섞인 안내는 자동 변경을 보류합니다. 배송 안내를 별도 자료로 분리해 확인하세요.');f.content=f.content.replace(amountPatterns(),match=>/오만/.test(match)?'삼만 원':/만/.test(match)?'3만원':'30000');}else if(f.scope==='config'){const config=JSON.parse(f.content);if(config.freeShippingMinimum!==50000&&config.freeShippingMinimum!==30000)throw Error('설정의 기존 기준이 5만원이 아닙니다.');config.freeShippingMinimum=30000;f.content=JSON.stringify(config,null,2);}}return copy;}
 function checkProject(p){project(p);const findings=[];let config=null;for(const f of p.artifacts){if(f.scope==='general'&&amountPatterns().test(f.content))findings.push({path:f.path,reason:'이전 금액 표현이 남았습니다. 문맥을 확인하세요.'});if(f.scope==='review')findings.push({path:f.path,reason:'일반 고객 배송과의 관계가 아직 확정되지 않았습니다.'});if(f.scope==='config'){if(config)throw Error('설정 파일은 하나만 지원합니다.');config=JSON.parse(f.content);if(config.freeShippingMinimum!==30000)findings.push({path:f.path,reason:'계산 설정이 새 기준과 다릅니다.'});}}
  const tests=p.artifacts.filter(f=>f.scope==='tests').flatMap(f=>JSON.parse(f.content));if(!config)findings.push({path:'설정',reason:'배송 계산 설정이 없습니다.'});if(!config||!Number.isFinite(config.freeShippingMinimum)||!Number.isFinite(config.shippingFee)||config.shippingFee<0||config.freeShippingMinimum<0)throw Error('설정에는 0 이상 숫자 freeShippingMinimum, shippingFee가 필요합니다.');
  const results=tests.map(t=>{if(!Number.isFinite(t.amount)||!Number.isFinite(t.expectedFee))throw Error('테스트에는 숫자 amount, expectedFee가 필요합니다.');const fee=t.amount>=config.freeShippingMinimum?0:config.shippingFee;return {...t,actualFee:fee,pass:fee===t.expectedFee};});for(const t of results)if(!t.pass)findings.push({path:'tests',reason:t.amount+'원 배송비가 기대값과 다릅니다.'});for(const amount of [29999,30000])if(!results.some(t=>t.amount===amount))findings.push({path:'tests',reason:amount+'원 경계값 검증이 빠졌습니다.'});return {findings,results,complete:findings.length===0};
 }
 function watch(records,event){if(!Array.isArray(event.files)||!Array.isArray(records)||!records.length)throw Error('files와 비어 있지 않은 판단 배열이 필요합니다.');const ids=new Set();return records.map(r=>{if(!r.id||ids.has(r.id)||!r.premise||!Array.isArray(r.prefixes)||!r.prefixes.length||r.prefixes.some(p=>typeof p!=='string'||!p.trim()))throw Error('판단에는 고유 id, premise, 비어 있지 않은 prefixes가 필요합니다.');ids.add(r.id);const files=event.files.filter(f=>r.prefixes.some(p=>f.path.startsWith(p)));return {...r,files,needsReview:files.length>0,reason:files.length?'판단과 연결된 경로에 실제 변경이 있습니다. 전제 유효성을 사람이 확인해야 합니다.':'지정 경로와 겹치는 변경이 없습니다. 전체 IP 검토 불필요 판정은 아닙니다.'};});}
 return {search,workflow,compare,outcomes,project,updateProject,checkProject,watch};
});
