/* Small working services using acquired public records and user-owned inputs. */
const S=window.SERVICE_ENGINE,by=id=>document.getElementById(id),html=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={home:['업무 서비스','U3 WORKSPACES'],b1:['장애 해결 기록','서비스 운영 담당자'],b2:['자동화 변경 검사','자동화 운영 담당자'],b3:['정책 변경 작업실','서비스 운영 담당자'],d:['공개 변경 검토함','R&D · IP 검토 담당자'],patent:['기술 문헌 검토','기술 조사 담당자']};
const key='u3-working-services-v1';let data,notice='',busy=false,downloadUrl='';let st={topic:'home',incidentQuery:'소문자 명령 인식 오류',incidentHits:[],incidentId:'',incidentReason:'',incidentRecords:[],flowA:'',flowB:'',flowOrigins:{flowA:'검증 실행에서 추출한 초기 자료',flowB:'검증 실행에서 추출한 초기 자료'},flowAnalysis:null,flowResults:null,flowReason:'',flowRecords:[],project:null,file:'policy.md',drafts:{},selected:[],projectCheck:null,projectReason:'',projectRecords:[],decisions:JSON.stringify([{id:'SDK-001',prefixes:['sentry_sdk/integrations/'],premise:'예시 전제: 이전 SDK 버전의 통합 모듈을 기준으로 검토했다. 새 모듈이 추가되면 담당자가 공개 범위를 다시 확인한다.'}],null,2),event:null,watched:null,eventReasons:{},eventChoices:{},eventRecords:[],patentQuery:'거리측정 오브젝트 인식',ipc:'',before:'',patentHits:[],patentId:'',patentReason:'',patentChoice:'review',patentRecords:[]};
try{const saved=JSON.parse(localStorage.getItem(key)||'null');if(saved&&saved.version===1)st={...st,...saved.state};}catch{notice='저장 기록을 읽지 못했습니다. 새 작업으로 시작합니다.';}
function save(){try{localStorage.setItem(key,JSON.stringify({version:1,state:st}));}catch{notice='브라우저 저장 공간이 부족합니다. 작업 결과를 내보내 주세요.';}}
function panel(title,body){return `<section class="panel"><h3>${html(title)}</h3>${body}</section>`;}
function computed(title,body){return '<div data-stale>'+panel(title,body)+'</div>';}
function button(action,text,disabled=false,secondary=false){return `<button class="${secondary?'secondary':'primary'}" data-do="${action}" ${disabled?'disabled':''}>${html(text)}</button>`;}
function area(id,label,value,code=false){return `<label for="${id}">${html(label)}</label><textarea id="${id}" data-input="${id}" class="${code?'service-code':''}">${html(value)}</textarea>`;}
function input(id,label,value,type='text'){return `<label for="${id}">${html(label)}</label><input id="${id}" type="${type}" data-input="${id}" value="${html(value)}">`;}
function upload(kind,label){return `<label class="import-label">${html(label)}<input type="file" accept=".json,application/json" data-upload="${kind}"></label>`;}
function source(text){return `<p class="source-note">${html(text)}</p>`;}
function empty(text){return `<div class="service-empty">${html(text)}</div>`;}
function records(rows,label){return rows.length?`<details><summary>${html(label)} · ${rows.length}건</summary><ul class="audit-list">${rows.slice().reverse().map(r=>`<li><strong>${html(r.title||r.id||r.at)}</strong><br>${html(r.reason)}<br><small>${html(r.at)}</small></li>`).join('')}</ul></details>`:'';}
function flowSummary(raw){try{const w=S.workflow(JSON.parse(raw));return '<p><strong>이 흐름이 바꾸는 정보</strong></p>'+ (w.writes.length?'<ul>'+w.writes.map(x=>'<li>'+html(x.field)+' → '+html(x.value)+'</li>').join('')+'</ul>':empty('지원 범위의 정적 쓰기가 없습니다.'))+source(w.unknown.length?'해석하지 못한 노드가 있습니다. 분석에서 보류 이유를 확인하세요.':'상태 필드 분리 버튼으로 CS 쓰기 이름을 바꾼 뒤 결과를 비교하세요.');}catch{return empty('정의를 확인해 주세요.');}}
function decisionForm(){try{const d=JSON.parse(st.decisions)[0];if(!d)return '';return '<p>첫 번째 판단: '+html(d.id)+'</p>'+area('decisionPremise','당시 판단의 전제',d.premise)+input('decisionPrefixes','관련 기술 경로 · 쉼표로 구분',d.prefixes.join(', '));}catch{return empty('상세 JSON 형식을 확인해 주세요.');}}
function render(){const main=by('service-main'),view=st.topic+':'+(st.chapter||0),same=main.dataset.view===view,listScroll=main.querySelector('.chapter-list')?.scrollTop||0;by('service-role').textContent=names[st.topic][1];by('service-title').textContent=names[st.topic][0];by('service-nav').innerHTML=Object.entries(names).map(([id,n])=>`<button data-go="${id}" class="${st.topic===id?'active':''}" aria-current="${st.topic===id?'page':'false'}">${html(n[0])}</button>`).join('');by('service-status').textContent=notice;by('service-main').innerHTML=chapterView();main.dataset.view=st.topic+':'+(st.chapter||0);if(same&&main.querySelector('.chapter-list'))main.querySelector('.chapter-list').scrollTop=listScroll;const surface=same?(main.querySelector('.chapter-split>.panel')||main):main;surface.getAnimations().forEach(a=>a.cancel());if(!matchMedia('(prefers-reduced-motion: reduce)').matches)surface.animate([{opacity:0,transform:'translateY(8px)'},{opacity:1,transform:'translateY(0)'}],{duration:220,easing:'ease-out'});}
function download(value,name){if(downloadUrl)URL.revokeObjectURL(downloadUrl);const text=JSON.stringify(value,null,2);downloadUrl=URL.createObjectURL(new Blob([text],{type:'application/json'}));const link=by('service-export-link');link.href=downloadUrl;link.download=name;link.textContent=name+' 다운로드';by('service-export-content').value=text;by('service-export').hidden=false;notice='현재 상태로 파일을 생성했습니다. 하단의 다운로드 링크 또는 파일 내용 확인을 사용하세요.';}
const reason=s=>{if(!String(s||'').trim())throw Error('검토 이유를 입력해 주세요.');return s.trim();};
function resetFlow(){st.flowAnalysis=null;st.flowResults=null;}
function resetProject(){st.projectCheck=null;}
async function action(id){if(busy)return;notice='';let succeeded=false;try{switch(id){
case 'incident-search':st.incidentHits=S.search(data.incidents,st.incidentQuery);st.incidentId=st.incidentHits[0]?.id||'';st.incidentReason='';notice=st.incidentHits.length?'관련 해결 기록을 찾았습니다. 적용 조건은 사람이 확인하세요.':'연결할 기록이 없습니다. 새로운 사건으로 추가 조사하세요.';break;
case 'incident-save':{const r=data.incidents.find(r=>r.id===st.incidentId);if(!r)throw Error('해결 기록을 선택하세요.');st.incidentRecords.push({id:r.id,title:r.title,query:st.incidentQuery,reason:reason(st.incidentReason),paths:r.paths,source:r.source,at:new Date().toISOString(),status:'검토된 처리 계획 · 복구 실행 미수행'});notice='처리 계획을 저장했습니다. 원본 코드 수정·복구 실행 결과는 별도로 확인해야 합니다.';break;}
case 'incident-export':download(st.incidentRecords,'incident-plans.json');break;
case 'flow-sample':st.flowA=JSON.stringify(data.flows[0],null,2);st.flowB=JSON.stringify(data.flows[1],null,2);st.flowOrigins={flowA:'검증 실행에서 추출한 초기 자료',flowB:'검증 실행에서 추출한 초기 자료'};resetFlow();break;
case 'flow-public':st.flowA=JSON.stringify(data.publicWorkflow,null,2);(st.flowOrigins||={}).flowA='공식 공개 워크플로 예제';resetFlow();notice='공식 공개 채팅 흐름을 가져왔습니다. 이 노드들의 업무 쓰기 의미는 지원하지 않아 보류됩니다.';break;
case 'flow-analyze':st.flowAnalysis=S.compare(JSON.parse(st.flowA),JSON.parse(st.flowB));st.flowResults=null;break;
case 'flow-split':{const flow=JSON.parse(st.flowB),nodes=flow.nodes.filter(n=>n.type==='n8n-nodes-base.httpRequest'&&!n.disabled);if(nodes.length!==1)throw Error('HTTP 쓰기 노드가 하나인 CS 흐름에서 지원합니다.');const node=nodes[0];if(node.parameters.sendBody!==true||node.parameters.specifyBody!=='json')throw Error('정적 JSON 본문이 필요합니다.');const body=JSON.parse(node.parameters.jsonBody);if(!Object.hasOwn(body,'status')||Object.hasOwn(body,'cs_status'))throw Error('status 필드가 있고 cs_status가 없는 자료에서 지원합니다.');body.cs_status=body.status;delete body.status;node.parameters.jsonBody=JSON.stringify(body);st.flowB=JSON.stringify(flow,null,2);(st.flowOrigins||={}).flowB='사용자가 CS 상태 필드를 분리한 자료 · 실행 미검증';resetFlow();notice='CS의 실제 JSON 본문을 cs_status 필드로 변경했습니다. 다시 분석해 결과를 확인하세요.';break;}
case 'flow-results':if(!st.flowAnalysis)throw Error('현재 정의를 먼저 분석하세요.');st.flowResults=S.outcomes(JSON.parse(st.flowA),JSON.parse(st.flowB));break;
case 'flow-record':if(!st.flowResults)throw Error('현재 정의로 결과를 계산하세요.');st.flowRecords.push({title:'자동화 변경 검토',reason:reason(st.flowReason),definitions:[JSON.parse(st.flowA),JSON.parse(st.flowB)],provenance:{...st.flowOrigins},analysis:st.flowAnalysis,results:st.flowResults,at:new Date().toISOString()});notice='현재 정의·계산 결과·판단 이유를 저장했습니다.';break;
case 'flow-export':download(st.flowRecords,'automation-reviews.json');break;
case 'project-sample':st.policyConfirmed=false;st.project=JSON.parse(JSON.stringify(data.project));st.file=st.project.artifacts[0].path;st.drafts={};st.selected=st.project.artifacts.filter(f=>['general','config'].includes(f.scope)).map(f=>f.path);resetProject();break;
case 'project-file-save':{const f=st.project.artifacts.find(f=>f.path===st.file);f.content=st.drafts[f.path]??f.content;delete st.drafts[f.path];resetProject();notice='작업 사본에 파일을 저장했습니다.';break;}
case 'project-apply':if(!st.selected.length)throw Error('반영할 파일을 선택하세요.');if(Object.keys(st.drafts).length)throw Error('편집 중인 파일을 먼저 저장하세요.');st.project=S.updateProject(st.project,st.selected);resetProject();notice='선택한 안내·설정 파일의 실제 문자열과 설정 값을 변경했습니다.';break;
case 'project-boundary':{if(Object.keys(st.drafts).length)throw Error('편집 중인 파일을 먼저 저장하세요.');const file=st.project.artifacts.find(f=>f.scope==='tests');if(!file)throw Error('tests 관계의 파일이 필요합니다.');const tests=JSON.parse(file.content),configFile=st.project.artifacts.find(f=>f.scope==='config');if(!configFile)throw Error('설정 파일이 필요합니다.');const fee=JSON.parse(configFile.content).shippingFee;if(!Number.isFinite(fee)||fee<0)throw Error('배송비 설정을 확인하세요.');for(const t of [{amount:29999,expectedFee:fee},{amount:30000,expectedFee:0}])if(!tests.some(x=>x.amount===t.amount))tests.push(t);file.content=JSON.stringify(tests,null,2);resetProject();notice='새 경계값을 추가했습니다. 기존 검사는 보존합니다.';break;}
case 'project-check':if(Object.keys(st.drafts).length)throw Error('편집 중인 파일을 먼저 저장하세요.');st.projectCheck=S.checkProject(st.project);break;
case 'project-record':if(!st.projectCheck?.complete)throw Error('현재 파일의 검사를 통과해야 합니다.');st.projectRecords.push({title:st.project.name,reason:reason(st.projectReason),at:new Date().toISOString(),project:JSON.parse(JSON.stringify(st.project)),checks:st.projectCheck});notice='사람의 완료 판단과 검사 결과를 저장했습니다.';break;
case 'project-export':if(Object.keys(st.drafts).length)throw Error('미저장 편집이 있습니다. 파일 사본을 먼저 저장하세요.');download({project:st.project,records:st.projectRecords},'shipping-project.json');break;
case 'event-watch':st.watched=S.watch(JSON.parse(st.decisions),st.event);st.eventChoices={};st.eventReasons={};break;
case 'event-refresh':{busy=true;notice='공개 SDK 버전과 변경을 조회하고 있습니다…';render();const get=async url=>{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),20000);try{const response=await fetch(url,{signal:controller.signal});if(!response.ok)throw Error('GitHub HTTP '+response.status);return await response.json();}finally{clearTimeout(timer);}};const releases=await get('https://api.github.com/repos/getsentry/sentry-python/releases?per_page=10');const stable=releases.filter(r=>!r.prerelease&&!r.draft);if(stable.length<2)throw Error('비교할 안정 버전 두 개를 확보하지 못했습니다.');const comparison=await get('https://api.github.com/repos/getsentry/sentry-python/compare/'+encodeURIComponent(stable[1].tag_name)+'...'+encodeURIComponent(stable[0].tag_name));if(!Array.isArray(comparison.files))throw Error('변경 파일이 응답에 없습니다.');st.event={repository:'getsentry/sentry-python',old_tag:stable[1].tag_name,new_tag:stable[0].tag_name,comparison_url:comparison.html_url,files:comparison.files.map(f=>({path:f.filename,status:f.status})),checkedAt:new Date().toISOString()};st.watched=null;st.eventChoices={};st.eventReasons={};notice='실제 공개 변경을 가져왔습니다. 과거 기록을 보존하고 전제 연결을 다시 확인하세요.';break;}
case 'event-record':if(!st.watched)throw Error('현재 판단과 변경을 연결하세요.');for(const r of st.watched){if(!['review','hold','skip'].includes(st.eventChoices[r.id]))throw Error(r.id+' 처리 방법을 선택하세요.');reason(st.eventReasons[r.id]);}st.eventRecords.push({title:st.event.old_tag+' → '+st.event.new_tag,reason:'담당자의 처리·전제 저장',event:st.event,decisions:st.watched.map(r=>({...r,choice:st.eventChoices[r.id],reason:st.eventReasons[r.id]})),at:new Date().toISOString()});notice='검토 이유와 이번 공개 사건을 함께 보존했습니다.';break;
case 'event-export':download(st.eventRecords,'disclosure-reviews.json');break;
case 'patent-search':{const cutoff=st.before.replace(/-/g,'');const corpus=data.patents.filter(r=>(!st.ipc||r.ipc.toLowerCase().includes(st.ipc.trim().toLowerCase()))&&(!cutoff||(r.publicDate&&r.publicDate<=cutoff)));st.patentHits=S.search(corpus,st.patentQuery);st.patentId=st.patentHits[0]?.id||'';st.patentReason='';notice=st.patentHits.length?'저장된 실제 문헌에서 후보를 찾았습니다.':'조건에 맞는 문헌이 없습니다. 조회 범위를 확대하거나 다른 조건을 입력하세요.';break;}
case 'patent-record':{const r=data.patents.find(r=>r.id===st.patentId);if(!r||!st.patentHits.some(h=>h.id===r.id))throw Error('현재 검색 후보를 선택하세요.');st.patentRecords.push({id:r.id,title:r.title,query:st.patentQuery,filters:{ipc:st.ipc,before:st.before},abstract:r.abstract,source:r.source,choice:st.patentChoice,reason:reason(st.patentReason),at:new Date().toISOString()});notice='실제 문헌과 검토 이유를 저장했습니다.';break;}
case 'patent-export':download(st.patentRecords,'patent-reviews.json');break;
}succeeded=true;save();}catch(error){notice='작업을 보류했습니다: '+error.message;}finally{busy=false;if(succeeded)advanceChapter(id);render();by('service-main').focus({preventScroll:true});}}
document.addEventListener('click',event=>{const t=event.target.closest('[data-go],[data-do],[data-incident],[data-file],[data-patent]');if(!t||busy)return;if(t.dataset.go){st.topic=t.dataset.go;st.chapter=0;by('service-export').hidden=true;location.hash=st.topic;notice='';save();render();by('service-main').focus();}else if(t.dataset.do)action(t.dataset.do);else if(t.dataset.incident){st.incidentId=t.dataset.incident;st.incidentReason='';st.chapter=1;render();}else if(t.dataset.file){st.file=t.dataset.file;render();}else if(t.dataset.patent){st.patentId=t.dataset.patent;st.patentReason='';st.chapter=1;render();}});
document.addEventListener('input',event=>{const t=event.target,id=t.dataset.input;if(id){by('service-export').hidden=true;if(['decisionPremise','decisionPrefixes','incidentQuery','flowA','flowB','fileDraft','fileScope','decisions','patentQuery','ipc','before'].includes(id)){const hint=by('service-main').querySelector('.journey-guide span');if(hint)hint.textContent='입력이 바뀌었습니다. 저장·검색·분석을 다시 실행해 현재 자료의 결과를 확인하세요.';}if(['decisionPremise','decisionPrefixes'].includes(id)){try{const rows=JSON.parse(st.decisions);if(id==='decisionPremise')rows[0].premise=t.value;else rows[0].prefixes=t.value.split(',').map(x=>x.trim()).filter(Boolean);st.decisions=JSON.stringify(rows,null,2);by('decisions').value=st.decisions;st.watched=null;by('service-main').querySelectorAll('[data-stale]').forEach(el=>el.hidden=true);save();by('service-status').textContent='전제가 바뀌었습니다. 실제 변경과 다시 연결하세요.';}catch{notice='상세 JSON 형식을 먼저 확인하세요.';}return;}if(id==='fileDraft'){st.drafts[st.file]=t.value;resetProject();}else if(id==='fileScope'){st.project.artifacts.find(f=>f.path===st.file).scope=t.value;resetProject();}else{st[id]=t.value;if(['flowA','flowB'].includes(id)){(st.flowOrigins||={})[id]='사용자 편집 자료 · 실행 미검증';resetFlow();}if(id==='decisions')st.watched=null;if(id==='incidentQuery'){st.incidentHits=[];st.incidentId='';}if(['patentQuery','ipc','before'].includes(id)){st.patentHits=[];st.patentId='';}}if(['incidentQuery','flowA','flowB','fileDraft','fileScope','decisions','patentQuery','ipc','before'].includes(id)){by('service-main').querySelectorAll('[data-stale]').forEach(el=>el.hidden=true);if(id==='incidentQuery')by('service-main').querySelectorAll('[data-incident]').forEach(el=>el.hidden=true);by('service-status').textContent='입력이 바뀌었습니다. 현재 자료로 다시 처리해 주세요.';}save();}else if(t.dataset.eventReason){st.eventReasons[t.dataset.eventReason]=t.value;save();}});
document.addEventListener('change',async event=>{const t=event.target;if(t.dataset.selectFile){const p=t.dataset.selectFile;st.selected=t.checked?[...new Set([...st.selected,p])]:st.selected.filter(x=>x!==p);save();}if(t.dataset.eventChoice){st.eventChoices[t.dataset.eventChoice]=t.value;save();}if(t.dataset.upload){try{const file=t.files[0];if(!file)return;if(file.size>3000000)throw Error('파일은 3MB 이하만 지원합니다.');const value=JSON.parse(await file.text()),kind=t.dataset.upload;if(kind==='project'){st.policyConfirmed=false;const p=value.project||value;S.project(p);st.project={...p,kind:'uploaded'};st.file=p.artifacts[0].path;st.drafts={};st.selected=[];resetProject();}else if(kind==='decisions'){S.watch(value,st.event);st.decisions=JSON.stringify(value,null,2);st.watched=null;}else{S.workflow(value);st[kind]=JSON.stringify(value,null,2);(st.flowOrigins||={})[kind]='사용자 가져오기: '+file.name+' · 실행 미검증';resetFlow();}save();notice='자료를 가져왔습니다. 현재 입력으로 다시 확인하세요.';}catch(error){notice='가져오기를 보류했습니다: '+error.message;}render();}});
const help={home:'업무를 선택하면 세 단계로 진행합니다. 입력과 판단 기록은 이 브라우저에 저장됩니다.',b1:'발생한 오류를 입력하세요. 공개 해결 사례에서 이번 오류와 비슷한 조건을 확인한 뒤, 적용할 조건과 처리 계획을 기록합니다. 실제 복구는 별도 확인이 필요합니다.',b2:'마케팅과 상담 자동화가 같은 고객 상태를 바꾸는지 확인합니다. 순서를 바꿨을 때 결과가 달라지면 상담 상태를 따로 관리해 다시 비교하세요. 이 화면은 정의를 비교하며 실제 고객 시스템을 실행하지 않습니다.',b3:'일반 고객의 무료배송 기준을 5만원에서 3만원으로 바꿉니다. 안내와 설정을 확인하고 변경하세요. 누락 검사에서 빠진 안내와 새 기준 전후 금액을 보정한 뒤 완료 이유를 남깁니다. 작업 사본에만 반영됩니다.',d:'이전에 판단한 조건과 확인할 기술 범위를 정하세요. 실제 공개 변경에서 관련 항목을 찾고, 다시 검토할지 또는 정보가 부족한지 이유와 함께 기록합니다. 법적 결론을 대신하지 않습니다.',patent:'기술 설명으로 문헌을 찾으세요. 후보의 실제 초록을 읽고 우리 기술과의 공통점과 차이를 확인한 뒤 검토 여부를 기록합니다. 확보한 문헌 저장본을 검색하며 전체 실시간 특허 검색은 아닙니다.'};
by('service-export-close').onclick=()=>by('service-export').hidden=true;
by('service-help').onclick=()=>{by('service-help-title').textContent=names[st.topic][0]+' · 사용 안내';by('service-help-body').innerHTML=`<p>${html(help[st.topic])}</p><p>입력은 이 브라우저에 저장됩니다. 외부 제출이나 자동 배포는 없습니다.</p>`;by('service-dialog').showModal();};by('service-help-close').onclick=()=>by('service-dialog').close();
window.addEventListener('hashchange',()=>{const id=location.hash.slice(1);if(data&&names[id]&&st.topic!==id){st.topic=id;st.chapter=0;render();}});
fetch('service-data.json').then(r=>{if(!r.ok)throw Error('HTTP '+r.status);return r.json();}).then(value=>{data=value;if(st.incidentQuery==='ascii.qdp read serr')st.incidentQuery='소문자 명령 인식 오류';if(!st.project){st.project=JSON.parse(JSON.stringify(data.project));st.selected=st.project.artifacts.filter(f=>['general','config'].includes(f.scope)).map(f=>f.path);}if(!st.event)st.event=data.sdk;if(!st.flowA){st.flowA=JSON.stringify(data.flows[0],null,2);st.flowB=JSON.stringify(data.flows[1],null,2);}const id=location.hash.slice(1);if(names[id])st.topic=id;if(!names[st.topic])st.topic='home';render();}).catch(error=>{by('service-main').innerHTML=empty('자료를 불러오지 못했습니다. 새로고침해서 다시 시도하세요.');by('service-status').textContent=error.message;});
