/* Small working services using acquired public records and user-owned inputs. */
const S=window.SERVICE_ENGINE,by=id=>document.getElementById(id),html=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={home:['업무 서비스','U3 WORKSPACES'],b1:['장애 해결 기록','서비스 운영 담당자'],b2:['자동화 변경 검사','자동화 운영 담당자'],b3:['정책 변경 작업실','서비스 운영 담당자'],d:['공개 변경 검토함','R&D · IP 검토 담당자'],patent:['기술 문헌 검토','기술 조사 담당자']};
const key='u3-working-services-v1';let data,notice='',busy=false,downloadUrl='';let st={topic:'home',incidentQuery:'ascii.qdp read serr',incidentHits:[],incidentId:'',incidentReason:'',incidentRecords:[],flowA:'',flowB:'',flowOrigins:{flowA:'검증 실행에서 추출한 초기 자료',flowB:'검증 실행에서 추출한 초기 자료'},flowAnalysis:null,flowResults:null,flowReason:'',flowRecords:[],project:null,file:'policy.md',drafts:{},selected:[],projectCheck:null,projectReason:'',projectRecords:[],decisions:JSON.stringify([{id:'SDK-001',prefixes:['sentry_sdk/integrations/'],premise:'예시 전제: 이전 SDK 버전의 통합 모듈을 기준으로 검토했다. 새 모듈이 추가되면 담당자가 공개 범위를 다시 확인한다.'}],null,2),event:null,watched:null,eventReasons:{},eventChoices:{},eventRecords:[],patentQuery:'거리측정 오브젝트 인식',ipc:'',before:'',patentHits:[],patentId:'',patentReason:'',patentChoice:'review',patentRecords:[]};
try{const saved=JSON.parse(localStorage.getItem(key)||'null');if(saved&&saved.version===1)st={...st,...saved.state};}catch{notice='저장 기록을 읽지 못했습니다. 새 작업으로 시작합니다.';}
function save(){try{localStorage.setItem(key,JSON.stringify({version:1,state:st}));}catch{notice='브라우저 저장 공간이 부족합니다. 작업 결과를 내보내 주세요.';}}
function panel(title,body){return `<section class="panel"><h3>${html(title)}</h3>${body}</section>`;}
function computed(title,body){return '<div data-stale>'+panel(title,body)+'</div>';}
function button(action,text,disabled=false,secondary=false){return `<button class="${secondary?'secondary':'primary'}" data-do="${action}" ${disabled?'disabled':''}>${html(text)}</button>`;}
function area(id,label,value,code=false){return `<label for="${id}">${html(label)}</label><textarea id="${id}" data-input="${id}" class="${code?'service-code':''}">${html(value)}</textarea>`;}
function input(id,label,value,type='text'){return `<label for="${id}">${html(label)}</label><input id="${id}" type="${type}" data-input="${id}" value="${html(value)}">`;}
function upload(kind,label){return `<label class="import-label">${html(label)}<input type="file" accept=".json,application/json" data-upload="${kind}"></label>`;}
function source(text){return `<p class="source-note">${html(text)}</p>`;}
function empty(text){return `<div class="service-empty">${html(text)}</div>`;}
function records(rows,label){return rows.length?`<details><summary>${html(label)} · ${rows.length}건</summary><ul class="audit-list">${rows.slice().reverse().map(r=>`<li><strong>${html(r.title||r.id||r.at)}</strong><br>${html(r.reason)}<br><small>${html(r.at)}</small></li>`).join('')}</ul></details>`:'';}
function home(){const details={b1:['오류를 만났을 때','공개 해결 이력을 찾아 적용 조건·처리 계획을 기록합니다.','실제 오류·수정 기록 3건'],b2:['자동화를 추가하기 전에','JSON의 공유 쓰기를 찾아 수정 전후 결과를 계산합니다.','실제 n8n 정의·실행 근거'],b3:['배송 정책을 바꿀 때','파일 사본을 반영하고 누락·배송 경계값을 검사합니다.','파일 입력·실제 로컬 계산'],d:['기술의 공개 범위가 바뀔 때','실제 SDK 변경과 기록한 판단 전제를 연결합니다.','공개 SDK 변경 41개 파일'],patent:['기술 관련 문헌을 찾을 때','실제 문헌을 검색하고 초록 근거·검토 이유를 남깁니다.',`KIPRIS 조회 문헌 ${data.patents.length.toLocaleString()}건`]};return `<div class="service-intro"><span class="eyebrow">YOUR WORK, ONE STEP FURTHER</span><h2>지금 처리할 업무를 선택하세요.</h2><p>자료를 확인하고, 직접 수정하고, 처리 결과를 가져갈 수 있습니다. 각 작업 공간의 기록은 별도로 보관됩니다.</p></div><div class="service-grid">${Object.entries(details).map(([id,x])=>panel(names[id][0],`<p>${html(x[0])}</p><p>${html(x[1])}</p><div class="service-meta"><span>${html(x[2])}</span></div><button class="primary" data-go="${id}">작업 공간 열기 →</button>`)).join('')}</div>`;}
function incident(){const chosen=data.incidents.find(x=>x.id===st.incidentId);return `<div class="service-intro"><h2>같은 오류를 다시 조사하지 않도록.</h2><p>실패 메시지에서 과거 해결 기록을 찾고, 이번 사건에 적용할 조건을 검토하세요.</p></div><div class="workspace-columns">${panel('실패 사건 입력',area('incidentQuery','오류 메시지 또는 조사할 기능',st.incidentQuery)+`<div class="service-actions">${button('incident-search','해결 기록 찾기')}</div>`+source('SWE-bench 공개 astropy 사례 3건을 비교합니다. 주문 자료와 자동 복구 도구는 아닙니다.')+st.incidentHits.map(hit=>`<button class="service-item ${hit.id===st.incidentId?'selected':''}" data-incident="${html(hit.id)}"><strong>${html(hit.title)}</strong><small>연결 단어: ${html(hit.matches.join(', '))}</small></button>`).join(''))}${chosen?computed('해결 근거와 이번 처리 계획',`<h3>${html(chosen.title)}</h3><p>${html(chosen.summary)}</p><p><strong>수정된 파일</strong></p><ul>${chosen.paths.map(p=>`<li>${html(p)}</li>`).join('')}</ul><details><summary>원본 기록의 검증 대상 테스트</summary><pre>${html(chosen.tests.join('\n'))}</pre></details><p><a href="${chosen.source}" target="_blank" rel="noopener">공개 해결 기록 원문</a></p>${source(chosen.limit)}${area('incidentReason','이번 입력의 조건·차이와 처리 계획',st.incidentReason)}<div class="service-actions">${button('incident-save','검토한 처리 계획 저장')}${button('incident-export','처리 계획 내보내기',!st.incidentRecords.length,true)}</div>${records(st.incidentRecords,'저장한 처리 계획')}`):empty(st.incidentHits.length?'해결 기록을 선택해 적용 조건과 수정 근거를 확인하세요.':'오류 메시지를 입력해 해결 기록을 검색하세요.')}</div>`;}
function flows(){const a=st.flowAnalysis;return `<div class="service-intro"><h2>각자 정상인 흐름, 함께 실행해도 괜찮을까요?</h2><p>두 자동화의 정적 HTTP 쓰기를 비교합니다. URL·본문을 고치면 분석과 결과 계산도 다시 해야 합니다.</p></div><div class="service-grid">${panel('마케팅 흐름',flowSummary(st.flowA)+'<details><summary>정의 확인·수정 또는 파일 가져오기</summary>'+area('flowA','첫 번째 n8n JSON',st.flowA,true)+upload('flowA','JSON 파일 가져오기')+'</details>')}${panel('CS 흐름',flowSummary(st.flowB)+'<details><summary>정의 확인·수정 또는 파일 가져오기</summary>'+area('flowB','두 번째 n8n JSON',st.flowB,true)+upload('flowB','JSON 파일 가져오기')+'</details>')}</div><div class="service-actions">${button('flow-analyze','공유 쓰기 분석')}${button('flow-sample','검증한 HTTP 흐름 불러오기',false,true)}${button('flow-public','공개 워크플로 구조 불러오기',false,true)}${button('flow-split','CS 상태 필드 분리',false,true)}${button('flow-results','두 실행 순서 결과 계산',!a||a.unknown.length>0)}</div>${source('입력 출처: A '+(st.flowOrigins?.flowA||'사용자 저장 자료')+' / B '+(st.flowOrigins?.flowB||'사용자 저장 자료')+'. 초기 예제의 URL은 example.test로 치환했습니다. 외부 API를 실행하지 않는 정적 분석입니다. n8n 별도 실행 '+data.n8nEvidence.runs+'건은 검증 기록에서 확인할 수 있습니다.')}${a?computed('분석 결과',`<div class="service-meta"><span>A 쓰기 ${a.a.writes.length}개</span><span>B 쓰기 ${a.b.writes.length}개</span><span>충돌 후보 ${a.conflicts.length}개</span><span>미해석 ${a.unknown.length}개</span></div>${a.unknown.length?`<div class="services-warning">분석을 보류해야 할 항목<ul>${a.unknown.map(x=>`<li>${html(x)}</li>`).join('')}</ul>동적 URL·표현식·Code/LLM 노드는 이 버전에서 해석하지 않습니다.</div>`:''}${a.conflicts.length?`<ul class="audit-list">${a.conflicts.map(x=>`<li><strong>${html(x.field)} · ${html(x.kind)}</strong><br>${html(x.resource)}<br>A: ${html(x.first)} / B: ${html(x.second)}</li>`).join('')}</ul>`:'<p>지원한 쓰기 범위에서 겹치는 필드가 없습니다. 미해석 항목이 있으면 전체 충돌 없음으로 판단할 수 없습니다.</p>'}${st.flowResults?`<div class="diff-grid"><div><h4>A → B</h4><pre>${html(JSON.stringify(st.flowResults.ab,null,2))}</pre></div><div><h4>B → A</h4><pre>${html(JSON.stringify(st.flowResults.ba,null,2))}</pre></div></div>${source(st.flowResults.note)}`:''}${area('flowReason','필드 분리·실행 조건에 대한 판단 이유',st.flowReason)}<div class="service-actions">${button('flow-record','변경 검토 기록 저장',!st.flowResults)}${button('flow-export','검토 결과 내보내기',!st.flowRecords.length,true)}</div>${records(st.flowRecords,'자동화 변경 검토 이력')}`):empty('두 정의를 확인하고 공유 쓰기를 분석하세요. 공개 채팅 워크플로는 구조를 읽을 수 있지만 쓰기 결과 계산을 지원하지 않습니다.')}`;}
function projectView(){const p=st.project,f=p.artifacts.find(a=>a.path===st.file)||p.artifacts[0],check=st.projectCheck;return `<div class="service-intro"><h2>5만원에서 3만원으로, 자료와 계산을 함께 바꾸세요.</h2><p>지원 업무는 일반 고객 무료배송 기준 변경입니다. 관계를 지정한 파일 사본을 수정하고 실제 배송비 함수를 실행합니다.</p></div><div class="service-actions">${button('project-sample','배송 작업 사본 불러오기',false,true)}${upload('project','프로젝트 JSON 가져오기')}${button('project-export','현재 프로젝트 내보내기',false,true)}</div>${source(p.kind==='controlled'?'통제된 배송 프로젝트 파일입니다. 실제 회사 자료는 프로젝트 JSON으로 가져올 수 있습니다.':'사용자가 가져온 파일 사본입니다. 원본 서비스에는 반영되지 않습니다.')}<div class="workspace-columns">${panel(p.name||'프로젝트',p.artifacts.map(a=>`<button class="secondary file-button ${a.path===f.path?'active':''}" data-file="${html(a.path)}">${html(a.path)} · ${html(({general:'배송 안내',config:'계산 설정',tests:'배송비 검사',unrelated:'무관',review:'관계 미확인'})[a.scope])}</button>`).join(''))}${panel(f.path,`<label for="fileScope">변경 요청과의 관계</label><select id="fileScope" data-input="fileScope">${[['general','일반 고객 배송 안내'],['config','배송 계산 설정'],['tests','배송비 검사'],['unrelated','무관 항목'],['review','관계 확인 필요']].map(([v,l])=>`<option value="${v}" ${f.scope===v?'selected':''}>${l}</option>`).join('')}</select>${area('fileDraft','파일 내용',st.drafts[f.path]??f.content,true)}<div class="service-actions">${button('project-file-save','파일 사본 저장',false,true)}</div><label><input type="checkbox" data-select-file="${html(f.path)}" ${st.selected.includes(f.path)?'checked':''}>금액 변경 반영 대상에 포함</label><p class="small">관계는 사람이 확정합니다. 무관 항목과 테스트는 자동 금액 치환에서 제외합니다.</p>`)}</div><div class="service-actions">${button('project-apply','선택 파일에 금액 변경 반영')}${button('project-boundary','새 경계값 검사 추가',false,true)}${button('project-check','파일·배송비 검사')}</div>${check?computed('변경 확인 결과',`<h4>${check.complete?'지원 검사 통과 · 완료 판단 가능':'보정할 항목이 남았습니다'}</h4><ul>${check.findings.map(x=>`<li>${html(x.path)}: ${html(x.reason)}</li>`).join('')}</ul><div class="service-table-wrap"><table class="service-table"><thead><tr><th>주문 금액</th><th>기대 배송비</th><th>실제 계산</th><th>검사</th></tr></thead><tbody>${check.results.map(t=>`<tr><td>${t.amount.toLocaleString()}원</td><td>${t.expectedFee}원</td><td>${t.actualFee}원</td><td>${t.pass?'통과':'실패'}</td></tr>`).join('')}</tbody></table></div><p>기존 5만원 테스트는 보존합니다. 검사 범위는 지정한 파일·금액 표현과 새 경계값입니다.</p>${area('projectReason','전체 반영 범위와 완료 판단 이유',st.projectReason)}<div class="service-actions">${button('project-record','변경 완료 기록',!check.complete)}</div>${records(st.projectRecords,'변경 기록')}`):''}`;}
function events(){return `<div class="service-intro"><h2>지난 판단의 전제가 지금도 유효한지.</h2><p>기술 변경을 실제 공개 자료에서 가져와, 사용자가 기록한 판단의 관련 경로와 연결합니다. IP 결론을 자동 판정하지 않습니다.</p></div><div class="service-grid">${panel('과거 판단 기록',decisionForm()+'<details><summary>여러 판단 기록·JSON 수정</summary>'+area('decisions','판단 JSON · id, prefixes, premise',st.decisions,true)+'</details>'+source('처음 표시한 판단은 입력 형식을 보여주는 예시입니다. 실제 회사 판단으로 사용하려면 본인 기록으로 바꿔 주세요.')+upload('decisions','판단 JSON 가져오기'))}${panel('확인할 공개 사건',`<h4>${html(st.event.repository)}</h4><p>${html(st.event.old_tag)} → ${html(st.event.new_tag)} · 변경 ${st.event.files.length}개</p><p><a href="${html(st.event.comparison_url)}" target="_blank" rel="noopener">실제 변경 원문</a></p>${button('event-refresh','최신 SDK 공개 변경 가져오기',busy,true)}${source('현재 자료: '+(st.event.checkedAt||data.generatedAt)+' · GitHub 공개 버전 비교. 공개 결정 기록과 내부 IP 판단은 별도입니다.')}<details><summary>변경 파일 보기</summary><ul>${st.event.files.map(f=>`<li>${html(f.path)} · ${html(f.status)}</li>`).join('')}</ul></details>`)}</div><div class="service-actions">${button('event-watch','판단 전제와 변경 연결')}</div>${st.watched?`<div data-stale class="service-items">${st.watched.map(r=>panel(r.id,`<p><strong>저장한 전제</strong> ${html(r.premise)}</p><p>${html(r.reason)}</p><ul>${r.files.map(f=>`<li>${html(f.path)} · ${html(f.status)}</li>`).join('')}</ul><label>담당자의 처리<select data-event-choice="${html(r.id)}"><option value="pending">판단 전</option>${[['review','검토 요청'],['hold','정보 부족 보류'],['skip','추가 검토 불필요']].map(([v,l])=>`<option value="${v}" ${st.eventChoices[r.id]===v?'selected':''}>${l}</option>`).join('')}</select></label><label>처리 이유<textarea data-event-reason="${html(r.id)}">${html(st.eventReasons[r.id]||'')}</textarea></label>`)).join('')}</div><div class="service-actions">${button('event-record','검토 기록 저장')}${button('event-export','검토함 내보내기',!st.eventRecords.length,true)}</div>${records(st.eventRecords,'이전 검토 기록')}`:''}`;}
function patents(){const doc=data.patents.find(r=>r.id===st.patentId);return `<div class="service-intro"><h2>실제 기술 문헌을 찾고, 검토 근거를 남기세요.</h2><p>기술 설명과 문헌의 제목·초록을 비교합니다. 검색 결과를 읽고 사람이 검토 대상과 차이를 결정합니다.</p></div>${panel('기술 검색',area('patentQuery','기술 설명 또는 검색어',st.patentQuery)+`<div class="service-grid">${input('ipc','IPC 분류 포함 조건 · 선택',st.ipc)}${input('before','공개일 상한 · 선택',st.before,'date')}</div><div class="service-actions">${button('patent-search','문헌 검색')}</div>`+source(`KIPRIS 실제 조회 ${data.patents.length.toLocaleString()}개 문헌의 저장본입니다. 거리측정·오브젝트/객체/물체 조회 범위이며 실시간 전체 특허 검색은 아닙니다. 제목·초록 단어 일치로 정렬합니다.`))}<div class="workspace-columns">${computed('검색 후보 '+st.patentHits.length+'건',st.patentHits.length?st.patentHits.slice(0,30).map(hit=>`<button class="service-item ${hit.id===st.patentId?'selected':''}" data-patent="${html(hit.id)}"><strong>${html(hit.title)}</strong><small>${html(hit.id)} · 일치 ${html(hit.matches.join(', '))}<br>공개일 ${html(hit.publicDate||'미확인')}</small></button>`).join('')+`<p class="small">상위 30개 표시. 조건을 좁혀 다른 후보를 확인하세요.</p>`:empty('조건에 맞는 문헌이 없거나 아직 검색하지 않았습니다. 검색어를 바꾸고 공개일·분류 조건을 확인하세요.'))}${doc?computed('문헌 근거 검토',`<span class="eyebrow">출원번호 ${html(doc.id)}</span><h3>${html(doc.title)}</h3><p>${html(doc.ipc)} · 공개일 ${html(doc.publicDate||'미확인')}</p><h4>실제 조회 초록</h4><p>${html(doc.abstract||'초록이 제공되지 않았습니다. 원문을 추가 확인해야 합니다.')}</p><p><a href="https://patents.google.com/?q=${encodeURIComponent(doc.title)}&country=KR" target="_blank" rel="noopener">제목으로 공개 원문 검색 ↗</a></p><p class="small">초록·제목만으로 청구항 범위나 신규성·침해 여부를 판단하지 않습니다.</p><label for="patentChoice">검토 처리</label><select id="patentChoice" data-input="patentChoice">${[['review','후속 검토 대상'],['hold','원문·추가 정보 확인'],['exclude','이번 기술 검토에서 제외']].map(([v,l])=>`<option value="${v}" ${st.patentChoice===v?'selected':''}>${l}</option>`).join('')}</select>${area('patentReason','초록 근거·우리 기술과의 공통점 또는 차이',st.patentReason)}<div class="service-actions">${button('patent-record','문헌 검토 저장')}${button('patent-export','검토 목록 내보내기',!st.patentRecords.length,true)}</div>${records(st.patentRecords,'문헌 검토 목록')}`):empty('후보를 선택하면 실제 초록과 기술 설명을 비교할 수 있습니다.')}</div>`;}
function flowSummary(raw){try{const w=S.workflow(JSON.parse(raw));return '<p><strong>이 흐름이 바꾸는 정보</strong></p>'+ (w.writes.length?'<ul>'+w.writes.map(x=>'<li>'+html(x.field)+' → '+html(x.value)+'</li>').join('')+'</ul>':empty('지원 범위의 정적 쓰기가 없습니다.'))+source(w.unknown.length?'해석하지 못한 노드가 있습니다. 분석에서 보류 이유를 확인하세요.':'상태 필드 분리 버튼으로 CS 쓰기 이름을 바꾼 뒤 결과를 비교하세요.');}catch{return empty('정의를 확인해 주세요.');}}
function decisionForm(){try{const d=JSON.parse(st.decisions)[0];if(!d)return '';return '<p>첫 번째 판단: '+html(d.id)+'</p>'+area('decisionPremise','당시 판단의 전제',d.premise)+input('decisionPrefixes','관련 기술 경로 · 쉼표로 구분',d.prefixes.join(', '));}catch{return empty('상세 JSON 형식을 확인해 주세요.');}}
function guide(){const options={b1:['오류 입력 → 근거 확인 → 처리 계획 보관',st.incidentHits.length?'원본 해결 조건과 이번 조건의 차이를 적고 저장하세요.':'실패 메시지를 입력하고 해결 기록을 찾으세요.'],b2:['현재 쓰기 확인 → 충돌 비교 → 보정 → 판단 보관',st.flowResults?'두 순서의 차이를 읽고 변경 이유를 저장하세요.':st.flowAnalysis?'미해석 항목을 확인하고, 지원 범위에서 실행 순서 결과를 계산하세요.':'공유 쓰기를 분석하세요. status 충돌을 확인한 뒤 CS 상태 필드를 분리해 다시 분석할 수 있습니다.'],b3:['대상 확인 → 파일 변경 → 경계값 검사 → 완료 판단',Object.keys(st.drafts).length?'편집한 파일 사본을 저장한 뒤 검사하세요.':st.projectCheck?.complete?'검사 범위를 확인하고 완료 판단 이유를 적어 기록하세요.':st.projectCheck?'검사 결과의 파일을 선택해 누락을 보정하고, 경계값 추가 후 다시 검사하세요.':'왼쪽 파일을 확인하고 반영 대상을 선택하세요. 변경 반영 후 파일·배송비 검사로 누락을 확인합니다.'],d:['과거 전제 확인 → 실제 변경 연결 → 검토 처리',st.watched?'각 변경에 검토 요청·보류·불필요를 선택하고 이유를 적어 저장하세요.':'전제와 관련 경로를 확인한 뒤 판단 전제와 변경 연결을 누르세요.'],patent:['기술 검색 → 초록 비교 → 검토 목록 보관',st.patentHits.length?'후보를 선택하고 실제 초록과 공통점·차이를 읽어 검토 이유를 저장하세요.':'기술 설명으로 검색하세요. 필요하면 분류와 공개일 조건을 좁히세요.']};const x=options[st.topic];return x?'<section class="journey-guide" aria-label="작업 흐름"><p>'+html(x[0])+'</p><strong>다음 작업</strong><span>'+html(x[1])+'</span></section>':'';}
function render(){by('service-role').textContent=names[st.topic][1];by('service-title').textContent=names[st.topic][0];by('service-nav').innerHTML=Object.entries(names).map(([id,n])=>`<button data-go="${id}" class="${st.topic===id?'active':''}" aria-current="${st.topic===id?'page':'false'}">${html(n[0])}</button>`).join('');by('service-status').textContent=notice;by('service-main').innerHTML=guide()+({home,b1:incident,b2:flows,b3:projectView,d:events,patent:patents}[st.topic])();}
function download(value,name){if(downloadUrl)URL.revokeObjectURL(downloadUrl);const text=JSON.stringify(value,null,2);downloadUrl=URL.createObjectURL(new Blob([text],{type:'application/json'}));const link=by('service-export-link');link.href=downloadUrl;link.download=name;link.textContent=name+' 다운로드';by('service-export-content').value=text;by('service-export').hidden=false;notice='현재 상태로 파일을 생성했습니다. 하단의 다운로드 링크 또는 파일 내용 확인을 사용하세요.';}
const reason=s=>{if(!String(s||'').trim())throw Error('검토 이유를 입력해 주세요.');return s.trim();};
function resetFlow(){st.flowAnalysis=null;st.flowResults=null;}
function resetProject(){st.projectCheck=null;}
async function action(id){if(busy)return;notice='';try{switch(id){
case 'incident-search':st.incidentHits=S.search(data.incidents,st.incidentQuery);st.incidentId=st.incidentHits[0]?.id||'';st.incidentReason='';notice=st.incidentHits.length?'관련 해결 기록을 찾았습니다. 적용 조건은 사람이 확인하세요.':'연결할 기록이 없습니다. 새로운 사건으로 추가 조사하세요.';break;
case 'incident-save':{const r=data.incidents.find(r=>r.id===st.incidentId);if(!r)throw Error('해결 기록을 선택하세요.');st.incidentRecords.push({id:r.id,title:r.title,query:st.incidentQuery,reason:reason(st.incidentReason),paths:r.paths,source:r.source,at:new Date().toISOString(),status:'검토된 처리 계획 · 복구 실행 미수행'});notice='처리 계획을 저장했습니다. 원본 코드 수정·복구 실행 결과는 별도로 확인해야 합니다.';break;}
case 'incident-export':download(st.incidentRecords,'incident-plans.json');break;
case 'flow-sample':st.flowA=JSON.stringify(data.flows[0],null,2);st.flowB=JSON.stringify(data.flows[1],null,2);st.flowOrigins={flowA:'검증 실행에서 추출한 초기 자료',flowB:'검증 실행에서 추출한 초기 자료'};resetFlow();break;
case 'flow-public':st.flowA=JSON.stringify(data.publicWorkflow,null,2);(st.flowOrigins||={}).flowA='공식 공개 워크플로 예제';resetFlow();notice='공식 공개 채팅 흐름을 가져왔습니다. 이 노드들의 업무 쓰기 의미는 지원하지 않아 보류됩니다.';break;
case 'flow-analyze':st.flowAnalysis=S.compare(JSON.parse(st.flowA),JSON.parse(st.flowB));st.flowResults=null;break;
case 'flow-split':{const flow=JSON.parse(st.flowB),nodes=flow.nodes.filter(n=>n.type==='n8n-nodes-base.httpRequest'&&!n.disabled);if(nodes.length!==1)throw Error('HTTP 쓰기 노드가 하나인 CS 흐름에서 지원합니다.');const node=nodes[0];if(node.parameters.sendBody!==true||node.parameters.specifyBody!=='json')throw Error('정적 JSON 본문이 필요합니다.');const body=JSON.parse(node.parameters.jsonBody);if(!Object.hasOwn(body,'status')||Object.hasOwn(body,'cs_status'))throw Error('status 필드가 있고 cs_status가 없는 자료에서 지원합니다.');body.cs_status=body.status;delete body.status;node.parameters.jsonBody=JSON.stringify(body);st.flowB=JSON.stringify(flow,null,2);(st.flowOrigins||={}).flowB='사용자가 CS 상태 필드를 분리한 자료 · 실행 미검증';resetFlow();notice='CS의 실제 JSON 본문을 cs_status 필드로 변경했습니다. 다시 분석해 결과를 확인하세요.';break;}
case 'flow-results':if(!st.flowAnalysis)throw Error('현재 정의를 먼저 분석하세요.');st.flowResults=S.outcomes(JSON.parse(st.flowA),JSON.parse(st.flowB));break;
case 'flow-record':if(!st.flowResults)throw Error('현재 정의로 결과를 계산하세요.');st.flowRecords.push({title:'자동화 변경 검토',reason:reason(st.flowReason),definitions:[JSON.parse(st.flowA),JSON.parse(st.flowB)],provenance:{...st.flowOrigins},analysis:st.flowAnalysis,results:st.flowResults,at:new Date().toISOString()});notice='현재 정의·계산 결과·판단 이유를 저장했습니다.';break;
case 'flow-export':download(st.flowRecords,'automation-reviews.json');break;
case 'project-sample':st.project=JSON.parse(JSON.stringify(data.project));st.file=st.project.artifacts[0].path;st.drafts={};st.selected=st.project.artifacts.filter(f=>['general','config'].includes(f.scope)).map(f=>f.path);resetProject();break;
case 'project-file-save':{const f=st.project.artifacts.find(f=>f.path===st.file);f.content=st.drafts[f.path]??f.content;delete st.drafts[f.path];resetProject();notice='작업 사본에 파일을 저장했습니다.';break;}
case 'project-apply':if(!st.selected.length)throw Error('반영할 파일을 선택하세요.');if(Object.keys(st.drafts).length)throw Error('편집 중인 파일을 먼저 저장하세요.');st.project=S.updateProject(st.project,st.selected);resetProject();notice='선택한 안내·설정 파일의 실제 문자열과 설정 값을 변경했습니다.';break;
case 'project-boundary':{if(Object.keys(st.drafts).length)throw Error('편집 중인 파일을 먼저 저장하세요.');const file=st.project.artifacts.find(f=>f.scope==='tests');if(!file)throw Error('tests 관계의 파일이 필요합니다.');const tests=JSON.parse(file.content),configFile=st.project.artifacts.find(f=>f.scope==='config');if(!configFile)throw Error('설정 파일이 필요합니다.');const fee=JSON.parse(configFile.content).shippingFee;if(!Number.isFinite(fee)||fee<0)throw Error('배송비 설정을 확인하세요.');for(const t of [{amount:29999,expectedFee:fee},{amount:30000,expectedFee:0}])if(!tests.some(x=>x.amount===t.amount))tests.push(t);file.content=JSON.stringify(tests,null,2);resetProject();notice='새 경계값을 추가했습니다. 기존 검사는 보존합니다.';break;}
case 'project-check':if(Object.keys(st.drafts).length)throw Error('편집 중인 파일을 먼저 저장하세요.');st.projectCheck=S.checkProject(st.project);break;
case 'project-record':if(!st.projectCheck?.complete)throw Error('현재 파일의 검사를 통과해야 합니다.');st.projectRecords.push({title:st.project.name,reason:reason(st.projectReason),at:new Date().toISOString(),project:JSON.parse(JSON.stringify(st.project)),checks:st.projectCheck});notice='사람의 완료 판단과 검사 결과를 저장했습니다.';break;
case 'project-export':if(Object.keys(st.drafts).length)throw Error('미저장 편집이 있습니다. 파일 사본을 먼저 저장하세요.');download({project:st.project,records:st.projectRecords},'shipping-project.json');break;
case 'event-watch':st.watched=S.watch(JSON.parse(st.decisions),st.event);st.eventChoices={};st.eventReasons={};break;
case 'event-refresh':{busy=true;notice='공개 SDK 버전과 변경을 조회하고 있습니다…';render();const get=async url=>{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),20000);try{const response=await fetch(url,{signal:controller.signal});if(!response.ok)throw Error('GitHub HTTP '+response.status);return await response.json();}finally{clearTimeout(timer);}};const releases=await get('https://api.github.com/repos/getsentry/sentry-python/releases?per_page=10');const stable=releases.filter(r=>!r.prerelease&&!r.draft);if(stable.length<2)throw Error('비교할 안정 버전 두 개를 확보하지 못했습니다.');const comparison=await get('https://api.github.com/repos/getsentry/sentry-python/compare/'+encodeURIComponent(stable[1].tag_name)+'...'+encodeURIComponent(stable[0].tag_name));if(!Array.isArray(comparison.files))throw Error('변경 파일이 응답에 없습니다.');st.event={repository:'getsentry/sentry-python',old_tag:stable[1].tag_name,new_tag:stable[0].tag_name,comparison_url:comparison.html_url,files:comparison.files.map(f=>({path:f.filename,status:f.status})),checkedAt:new Date().toISOString()};st.watched=null;st.eventChoices={};st.eventReasons={};notice='실제 공개 변경을 가져왔습니다. 과거 기록을 보존하고 전제 연결을 다시 확인하세요.';break;}
case 'event-record':if(!st.watched)throw Error('현재 판단과 변경을 연결하세요.');for(const r of st.watched){if(!['review','hold','skip'].includes(st.eventChoices[r.id]))throw Error(r.id+' 처리 방법을 선택하세요.');reason(st.eventReasons[r.id]);}st.eventRecords.push({title:st.event.old_tag+' → '+st.event.new_tag,reason:'담당자의 처리·전제 저장',event:st.event,decisions:st.watched.map(r=>({...r,choice:st.eventChoices[r.id],reason:st.eventReasons[r.id]})),at:new Date().toISOString()});notice='검토 이유와 이번 공개 사건을 함께 보존했습니다.';break;
case 'event-export':download(st.eventRecords,'disclosure-reviews.json');break;
case 'patent-search':{const cutoff=st.before.replace(/-/g,'');const corpus=data.patents.filter(r=>(!st.ipc||r.ipc.toLowerCase().includes(st.ipc.trim().toLowerCase()))&&(!cutoff||(r.publicDate&&r.publicDate<=cutoff)));st.patentHits=S.search(corpus,st.patentQuery);st.patentId=st.patentHits[0]?.id||'';st.patentReason='';notice=st.patentHits.length?'저장된 실제 문헌에서 후보를 찾았습니다.':'조건에 맞는 문헌이 없습니다. 조회 범위를 확대하거나 다른 조건을 입력하세요.';break;}
case 'patent-record':{const r=data.patents.find(r=>r.id===st.patentId);if(!r||!st.patentHits.some(h=>h.id===r.id))throw Error('현재 검색 후보를 선택하세요.');st.patentRecords.push({id:r.id,title:r.title,query:st.patentQuery,filters:{ipc:st.ipc,before:st.before},abstract:r.abstract,source:r.source,choice:st.patentChoice,reason:reason(st.patentReason),at:new Date().toISOString()});notice='실제 문헌과 검토 이유를 저장했습니다.';break;}
case 'patent-export':download(st.patentRecords,'patent-reviews.json');break;
}save();}catch(error){notice='작업을 보류했습니다: '+error.message;}finally{busy=false;render();if(['incident-search','flow-analyze','flow-results','project-check','event-watch','patent-search'].includes(id))by('service-main').querySelector('[data-stale]')?.scrollIntoView({behavior:'smooth',block:'start'});}}
document.addEventListener('click',event=>{const t=event.target.closest('[data-go],[data-do],[data-incident],[data-file],[data-patent]');if(!t||busy)return;if(t.dataset.go){st.topic=t.dataset.go;location.hash=st.topic;notice='';save();render();by('service-main').focus();}else if(t.dataset.do)action(t.dataset.do);else if(t.dataset.incident){st.incidentId=t.dataset.incident;st.incidentReason='';render();}else if(t.dataset.file){st.file=t.dataset.file;render();}else if(t.dataset.patent){st.patentId=t.dataset.patent;st.patentReason='';render();by('service-main').querySelectorAll('[data-stale]')[1]?.scrollIntoView({behavior:'smooth',block:'start'});}});
document.addEventListener('input',event=>{const t=event.target,id=t.dataset.input;if(id){by('service-export').hidden=true;if(['decisionPremise','decisionPrefixes','incidentQuery','flowA','flowB','fileDraft','fileScope','decisions','patentQuery','ipc','before'].includes(id)){const hint=by('service-main').querySelector('.journey-guide span');if(hint)hint.textContent='입력이 바뀌었습니다. 저장·검색·분석을 다시 실행해 현재 자료의 결과를 확인하세요.';}if(['decisionPremise','decisionPrefixes'].includes(id)){try{const rows=JSON.parse(st.decisions);if(id==='decisionPremise')rows[0].premise=t.value;else rows[0].prefixes=t.value.split(',').map(x=>x.trim()).filter(Boolean);st.decisions=JSON.stringify(rows,null,2);by('decisions').value=st.decisions;st.watched=null;by('service-main').querySelectorAll('[data-stale]').forEach(el=>el.hidden=true);save();by('service-status').textContent='전제가 바뀌었습니다. 실제 변경과 다시 연결하세요.';}catch{notice='상세 JSON 형식을 먼저 확인하세요.';}return;}if(id==='fileDraft'){st.drafts[st.file]=t.value;resetProject();}else if(id==='fileScope'){st.project.artifacts.find(f=>f.path===st.file).scope=t.value;resetProject();}else{st[id]=t.value;if(['flowA','flowB'].includes(id)){(st.flowOrigins||={})[id]='사용자 편집 자료 · 실행 미검증';resetFlow();}if(id==='decisions')st.watched=null;if(id==='incidentQuery'){st.incidentHits=[];st.incidentId='';}if(['patentQuery','ipc','before'].includes(id)){st.patentHits=[];st.patentId='';}}if(['incidentQuery','flowA','flowB','fileDraft','fileScope','decisions','patentQuery','ipc','before'].includes(id)){by('service-main').querySelectorAll('[data-stale]').forEach(el=>el.hidden=true);if(id==='incidentQuery')by('service-main').querySelectorAll('[data-incident]').forEach(el=>el.hidden=true);by('service-status').textContent='입력이 바뀌었습니다. 현재 자료로 다시 처리해 주세요.';}save();}else if(t.dataset.eventReason){st.eventReasons[t.dataset.eventReason]=t.value;save();}});
document.addEventListener('change',async event=>{const t=event.target;if(t.dataset.selectFile){const p=t.dataset.selectFile;st.selected=t.checked?[...new Set([...st.selected,p])]:st.selected.filter(x=>x!==p);save();}if(t.dataset.eventChoice){st.eventChoices[t.dataset.eventChoice]=t.value;save();}if(t.dataset.upload){try{const file=t.files[0];if(!file)return;if(file.size>3000000)throw Error('파일은 3MB 이하만 지원합니다.');const value=JSON.parse(await file.text()),kind=t.dataset.upload;if(kind==='project'){const p=value.project||value;S.project(p);st.project={...p,kind:'uploaded'};st.file=p.artifacts[0].path;st.drafts={};st.selected=[];resetProject();}else if(kind==='decisions'){S.watch(value,st.event);st.decisions=JSON.stringify(value,null,2);st.watched=null;}else{S.workflow(value);st[kind]=JSON.stringify(value,null,2);(st.flowOrigins||={})[kind]='사용자 가져오기: '+file.name+' · 실행 미검증';resetFlow();}save();notice='자료를 가져왔습니다. 현재 입력으로 다시 확인하세요.';}catch(error){notice='가져오기를 보류했습니다: '+error.message;}render();}});
const help={home:'업무를 선택하면 각각의 작업 공간이 열립니다. 입력 자료를 변경해 처리하고 결과를 JSON으로 보관할 수 있습니다.',b1:'오류 입력 → 연결 단어를 확인하며 공개 해결 기록 선택 → 이번 조건과 차이를 적어 처리 계획 저장. 단어 유사도는 해결책 재사용의 정답이 아닙니다. 원본 코드 적용과 테스트는 수행하지 않습니다.',b2:'실제 n8n JSON 두 개를 입력합니다. 지원 범위는 고정 URL과 정적 JSON HTTP 본문입니다. 같은 URL·필드에 서로 다른 값을 쓰면 충돌 후보를 표시합니다. CS 본문의 status를 cs_status로 바꿔 다시 분석하면 분리된 결과를 볼 수 있습니다. 실행 순서·분기·동적 노드·원격 시스템 동작을 보증하지 않는 제한된 덮어쓰기 모델입니다.',b3:'프로젝트 JSON에는 artifacts 배열과 path, content, scope가 필요합니다. scope: general 안내문, config 설정, tests 검사, unrelated 무관, review 미확인. 수정 파일 저장 → 대상 선택 → 5만원을 3만원으로 변경 → 경계값 추가 → 검사 → 사람의 완료 이유 기록 → 파일 내보내기. 파일의 완전한 영향 관계를 자동 탐색하지 않습니다. 원본 파일이나 회사 서비스에는 반영하지 않습니다.',d:'실제 공개 SDK 파일 변경을 사용합니다. 과거 판단은 id, prefixes(관련 경로), premise(전제)로 입력합니다. 겹치는 변경은 검토 시점 후보이며 법적 IP 판정이 아닙니다. 담당자의 처리와 이유를 저장하고 새 버전을 가져오면 다시 연결합니다. GitHub 응답은 변경 파일 목록이 최대 300개여서 대규모 비교는 추가 확인이 필요합니다.',patent:'KIPRIS 실제 조회 문헌 저장본에서 제목·초록 단어를 검색합니다. 오브젝트·객체·물체는 검색 표현을 정규화합니다. 공개일 상한을 지정하면 날짜가 없는 문헌은 제외됩니다. 후보 → 초록 근거 → 포함/보류/제외 이유 → 목록 저장·내보내기. 전체 KIPRIS 검색·청구항 심사·법적 판단은 수행하지 않습니다.'};
by('service-export-close').onclick=()=>by('service-export').hidden=true;
by('service-help').onclick=()=>{by('service-help-title').textContent=names[st.topic][0]+' · 사용 안내';by('service-help-body').innerHTML=`<p>${html(help[st.topic])}</p><p>입력은 이 브라우저에 저장됩니다. 외부 제출이나 자동 배포는 없습니다.</p>`;by('service-dialog').showModal();};by('service-help-close').onclick=()=>by('service-dialog').close();
window.addEventListener('hashchange',()=>{const id=location.hash.slice(1);if(data&&names[id]&&st.topic!==id){st.topic=id;render();}});
fetch('service-data.json').then(r=>{if(!r.ok)throw Error('HTTP '+r.status);return r.json();}).then(value=>{data=value;if(!st.project){st.project=JSON.parse(JSON.stringify(data.project));st.selected=st.project.artifacts.filter(f=>['general','config'].includes(f.scope)).map(f=>f.path);}if(!st.event)st.event=data.sdk;if(!st.flowA){st.flowA=JSON.stringify(data.flows[0],null,2);st.flowB=JSON.stringify(data.flows[1],null,2);}const id=location.hash.slice(1);if(names[id])st.topic=id;if(!names[st.topic])st.topic='home';render();}).catch(error=>{by('service-main').innerHTML=empty('자료를 불러오지 못했습니다. 새로고침해서 다시 시도하세요.');by('service-status').textContent=error.message;});
